apiVersion: loadbalancer.stackit.m.crossplane.io/v1alpha1
kind: ObservabilityCredential
metadata:
  annotations:
    meta.upbound.io/example-id: loadbalancer/v1alpha1/observabilitycredential
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    displayName: example-credentials
    password: example-password
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    username: example-user
