// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/intive/provider-stackit/apis/cluster/network/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Loadbalancer.
func (mg *Loadbalancer) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Networks); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Networks[i3].NetworkID),
			Extract:      resource.ExtractParamPath("network_id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Networks[i3].NetworkIDRef,
			Selector:     mg.Spec.ForProvider.Networks[i3].NetworkIDSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Networks[i3].NetworkID")
		}
		mg.Spec.ForProvider.Networks[i3].NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Networks[i3].NetworkIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Networks); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Networks[i3].NetworkID),
			Extract:      resource.ExtractParamPath("network_id", true),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Networks[i3].NetworkIDRef,
			Selector:     mg.Spec.InitProvider.Networks[i3].NetworkIDSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Networks[i3].NetworkID")
		}
		mg.Spec.InitProvider.Networks[i3].NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Networks[i3].NetworkIDRef = rsp.ResolvedReference

	}

	return nil
}
