// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ExportPolicyInitParameters struct {

	// (String) Name of the export policy.
	// Name of the export policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the export policy is associated.
	// STACKIT project ID to which the export policy is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes List) (see below for nested schema)
	Rules []RulesInitParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type ExportPolicyObservation struct {

	// It is structured as "project_id,region,policy_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the export policy.
	// Name of the export policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Export policy ID
	// Export policy ID
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// (String) STACKIT project ID to which the export policy is associated.
	// STACKIT project ID to which the export policy is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes List) (see below for nested schema)
	Rules []RulesObservation `json:"rules,omitempty" tf:"rules,omitempty"`
}

type ExportPolicyParameters struct {

	// (String) Name of the export policy.
	// Name of the export policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the export policy is associated.
	// STACKIT project ID to which the export policy is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Attributes List) (see below for nested schema)
	// +kubebuilder:validation:Optional
	Rules []RulesParameters `json:"rules,omitempty" tf:"rules,omitempty"`
}

type RulesInitParameters struct {

	// (String) Description of the Rule
	// Description of the Rule
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) IP access control list; IPs must have a subnet mask (e.g. "172.16.0.0/24" for a range of IPs, or "172.16.0.250/32" for a specific IP).
	// IP access control list; IPs must have a subnet mask (e.g. "172.16.0.0/24" for a range of IPs, or "172.16.0.250/32" for a specific IP).
	IPACL []*string `json:"ipAcl,omitempty" tf:"ip_acl,omitempty"`

	// (Number) Order of the rule within a Share Export Policy. The order is used so that when a client IP matches multiple rules, the first rule is applied
	// Order of the rule within a Share Export Policy. The order is used so that when a client IP matches multiple rules, the first rule is applied
	Order *float64 `json:"order,omitempty" tf:"order,omitempty"`

	// (Boolean) Flag to indicate if client IPs matching this rule can only mount the share in read only mode
	// Flag to indicate if client IPs matching this rule can only mount the share in read only mode
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Boolean) Flag to honor set UUID
	// Flag to honor set UUID
	SetUUID *bool `json:"setUuid,omitempty" tf:"set_uuid,omitempty"`

	// (Boolean) Flag to indicate if client IPs matching this rule have root access on the Share
	// Flag to indicate if client IPs matching this rule have root access on the Share
	SuperUser *bool `json:"superUser,omitempty" tf:"super_user,omitempty"`
}

type RulesObservation struct {

	// (String) Description of the Rule
	// Description of the Rule
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) IP access control list; IPs must have a subnet mask (e.g. "172.16.0.0/24" for a range of IPs, or "172.16.0.250/32" for a specific IP).
	// IP access control list; IPs must have a subnet mask (e.g. "172.16.0.0/24" for a range of IPs, or "172.16.0.250/32" for a specific IP).
	IPACL []*string `json:"ipAcl,omitempty" tf:"ip_acl,omitempty"`

	// (Number) Order of the rule within a Share Export Policy. The order is used so that when a client IP matches multiple rules, the first rule is applied
	// Order of the rule within a Share Export Policy. The order is used so that when a client IP matches multiple rules, the first rule is applied
	Order *float64 `json:"order,omitempty" tf:"order,omitempty"`

	// (Boolean) Flag to indicate if client IPs matching this rule can only mount the share in read only mode
	// Flag to indicate if client IPs matching this rule can only mount the share in read only mode
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Boolean) Flag to honor set UUID
	// Flag to honor set UUID
	SetUUID *bool `json:"setUuid,omitempty" tf:"set_uuid,omitempty"`

	// (Boolean) Flag to indicate if client IPs matching this rule have root access on the Share
	// Flag to indicate if client IPs matching this rule have root access on the Share
	SuperUser *bool `json:"superUser,omitempty" tf:"super_user,omitempty"`
}

type RulesParameters struct {

	// (String) Description of the Rule
	// Description of the Rule
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (List of String) IP access control list; IPs must have a subnet mask (e.g. "172.16.0.0/24" for a range of IPs, or "172.16.0.250/32" for a specific IP).
	// IP access control list; IPs must have a subnet mask (e.g. "172.16.0.0/24" for a range of IPs, or "172.16.0.250/32" for a specific IP).
	// +kubebuilder:validation:Optional
	IPACL []*string `json:"ipAcl" tf:"ip_acl,omitempty"`

	// (Number) Order of the rule within a Share Export Policy. The order is used so that when a client IP matches multiple rules, the first rule is applied
	// Order of the rule within a Share Export Policy. The order is used so that when a client IP matches multiple rules, the first rule is applied
	// +kubebuilder:validation:Optional
	Order *float64 `json:"order" tf:"order,omitempty"`

	// (Boolean) Flag to indicate if client IPs matching this rule can only mount the share in read only mode
	// Flag to indicate if client IPs matching this rule can only mount the share in read only mode
	// +kubebuilder:validation:Optional
	ReadOnly *bool `json:"readOnly,omitempty" tf:"read_only,omitempty"`

	// (Boolean) Flag to honor set UUID
	// Flag to honor set UUID
	// +kubebuilder:validation:Optional
	SetUUID *bool `json:"setUuid,omitempty" tf:"set_uuid,omitempty"`

	// (Boolean) Flag to indicate if client IPs matching this rule have root access on the Share
	// Flag to indicate if client IPs matching this rule have root access on the Share
	// +kubebuilder:validation:Optional
	SuperUser *bool `json:"superUser,omitempty" tf:"super_user,omitempty"`
}

// ExportPolicySpec defines the desired state of ExportPolicy
type ExportPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ExportPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ExportPolicyInitParameters `json:"initProvider,omitempty"`
}

// ExportPolicyStatus defines the observed state of ExportPolicy.
type ExportPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ExportPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ExportPolicy is the Schema for the ExportPolicys API. SFS export policy resource schema. Must have a region specified in the provider configuration. ~> This resource is in beta and may be subject to breaking changes in the future. Use with caution. See our guide https://registry.io/providers/stackitcloud/stackit/latest/docs/guides/opting_into_beta_resources for how to opt-in to use beta resources.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type ExportPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   ExportPolicySpec   `json:"spec"`
	Status ExportPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ExportPolicyList contains a list of ExportPolicys
type ExportPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ExportPolicy `json:"items"`
}

// Repository type metadata.
var (
	ExportPolicy_Kind             = "ExportPolicy"
	ExportPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ExportPolicy_Kind}.String()
	ExportPolicy_KindAPIVersion   = ExportPolicy_Kind + "." + CRDGroupVersion.String()
	ExportPolicy_GroupVersionKind = CRDGroupVersion.WithKind(ExportPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&ExportPolicy{}, &ExportPolicyList{})
}
