apiVersion: dns.stackit.crossplane.io/v1alpha1
kind: RecordSet
metadata:
  annotations:
    meta.upbound.io/example-id: dns/v1alpha1/recordset
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    comment: Example comment
    name: example-record-set
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    records:
    - 1.2.3.4
    type: A
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
