apiVersion: postgresflex.stackit.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: postgresflex/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example-postgresflex
  name: example-postgresflex
spec:
  forProvider:
    acl:
    - 193.148.160.0/19
    - 45.129.40.0/21
    backupSchedule: 0 0 * * *
    flavor:
      cpu: 2
      ram: 4
    name: example-postgresflex
    projectId: <PROJECT-ID>
    replicas: 1
    storage:
      class: premium-perf2-stackit
      size: 5
    version: "17"
