apiVersion: compute.stackit.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/group
  labels:
    testing.upbound.io/example-name: example-affinity-group
  name: example-affinity-group
spec:
  forProvider:
    name: example-affinity-group
    projectId: <PROJECT-ID>
    policy: soft-affinity
