apiVersion: compute.stackit.crossplane.io/v1alpha1
kind: Image
metadata:
  labels:
    testing.upbound.io/example-name: example-image
  name: example-image
spec:
  forProvider:
    name: example-image
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    diskFormat: qcow2
    localFilePath: ./path/to/image.qcow2
    minDiskSize: 10
    minRam: 512
  providerConfigRef:
    name: default
