apiVersion: compute.stackit.crossplane.io/v1alpha1
kind: NetworkInterfaceAttach
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/networkinterfaceattach
  labels:
    testing.upbound.io/example-name: example-nic-attach
  name: example-nic-attach
spec:
  forProvider:
    projectId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    serverIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-server
    networkInterfaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-network-interface
