apiVersion: compute.stackit.crossplane.io/v1alpha1
kind: Server
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/server
  labels:
    testing.upbound.io/example-name: example-server
  name: example-server
spec:
  forProvider:
    name: example-server
    projectId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    machineType: g2i.2
    availabilityZone: eu01-1
    bootVolume:
      sourceType: image
      sourceId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
      size: 64
