apiVersion: compute.stackit.crossplane.io/v1alpha1
kind: Volume
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/volume
  labels:
    testing.upbound.io/example-name: example-volume
  name: example-volume
spec:
  forProvider:
    name: example-volume
    projectId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    size: 64
    availabilityZone: eu01-1
