// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type CredentialInitParameters struct {

	// (String) The credential group ID.
	// The credential group ID.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/namespaced/objectstorage/v1alpha1.CredentialsGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("credentials_group_id",true)
	CredentialsGroupID *string `json:"credentialsGroupId,omitempty" tf:"credentials_group_id,omitempty"`

	// Reference to a CredentialsGroup in objectstorage to populate credentialsGroupId.
	// +kubebuilder:validation:Optional
	CredentialsGroupIDRef *v1.NamespacedReference `json:"credentialsGroupIdRef,omitempty" tf:"-"`

	// Selector for a CredentialsGroup in objectstorage to populate credentialsGroupId.
	// +kubebuilder:validation:Optional
	CredentialsGroupIDSelector *v1.NamespacedSelector `json:"credentialsGroupIdSelector,omitempty" tf:"-"`

	// 01-01T00:00:00Z". If not set, the credential never expires.
	// Expiration timestamp, in RFC339 format without fractional seconds. Example: "2025-01-01T00:00:00Z". If not set, the credential never expires.
	ExpirationTimestamp *string `json:"expirationTimestamp,omitempty" tf:"expiration_timestamp,omitempty"`

	// (String) STACKIT Project ID to which the credential group is associated.
	// STACKIT Project ID to which the credential group is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type CredentialObservation struct {

	// (String)
	AccessKey *string `json:"accessKey,omitempty" tf:"access_key,omitempty"`

	// (String) The credential ID.
	// The credential ID.
	CredentialID *string `json:"credentialId,omitempty" tf:"credential_id,omitempty"`

	// (String) The credential group ID.
	// The credential group ID.
	CredentialsGroupID *string `json:"credentialsGroupId,omitempty" tf:"credentials_group_id,omitempty"`

	// 01-01T00:00:00Z". If not set, the credential never expires.
	// Expiration timestamp, in RFC339 format without fractional seconds. Example: "2025-01-01T00:00:00Z". If not set, the credential never expires.
	ExpirationTimestamp *string `json:"expirationTimestamp,omitempty" tf:"expiration_timestamp,omitempty"`

	// It is structured as "project_id,region,credentials_group_id,credential_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT Project ID to which the credential group is associated.
	// STACKIT Project ID to which the credential group is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type CredentialParameters struct {

	// (String) The credential group ID.
	// The credential group ID.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/namespaced/objectstorage/v1alpha1.CredentialsGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("credentials_group_id",true)
	// +kubebuilder:validation:Optional
	CredentialsGroupID *string `json:"credentialsGroupId,omitempty" tf:"credentials_group_id,omitempty"`

	// Reference to a CredentialsGroup in objectstorage to populate credentialsGroupId.
	// +kubebuilder:validation:Optional
	CredentialsGroupIDRef *v1.NamespacedReference `json:"credentialsGroupIdRef,omitempty" tf:"-"`

	// Selector for a CredentialsGroup in objectstorage to populate credentialsGroupId.
	// +kubebuilder:validation:Optional
	CredentialsGroupIDSelector *v1.NamespacedSelector `json:"credentialsGroupIdSelector,omitempty" tf:"-"`

	// 01-01T00:00:00Z". If not set, the credential never expires.
	// Expiration timestamp, in RFC339 format without fractional seconds. Example: "2025-01-01T00:00:00Z". If not set, the credential never expires.
	// +kubebuilder:validation:Optional
	ExpirationTimestamp *string `json:"expirationTimestamp,omitempty" tf:"expiration_timestamp,omitempty"`

	// (String) STACKIT Project ID to which the credential group is associated.
	// STACKIT Project ID to which the credential group is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// CredentialSpec defines the desired state of Credential
type CredentialSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            CredentialParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CredentialInitParameters `json:"initProvider,omitempty"`
}

// CredentialStatus defines the observed state of Credential.
type CredentialStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CredentialObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Credential is the Schema for the Credentials API. ObjectStorage credential resource schema. Must have a region specified in the provider configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,stackit}
type Credential struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   CredentialSpec   `json:"spec"`
	Status CredentialStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CredentialList contains a list of Credentials
type CredentialList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Credential `json:"items"`
}

// Repository type metadata.
var (
	Credential_Kind             = "Credential"
	Credential_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Credential_Kind}.String()
	Credential_KindAPIVersion   = Credential_Kind + "." + CRDGroupVersion.String()
	Credential_GroupVersionKind = CRDGroupVersion.WithKind(Credential_Kind)
)

func init() {
	SchemeBuilder.Register(&Credential{}, &CredentialList{})
}
