apiVersion: rabbitmq.stackit.m.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example-rabbitmq
  name: example-rabbitmq
spec:
  forProvider:
    name: example-rabbitmq
    parameters:
      consumerTimeout: 18000000
      enableMonitoring: false
      plugins:
      - rabbitmq_consistent_hash_exchange
      - rabbitmq_federation
      - rabbitmq_tracing
      sgwAcl: 192.0.2.0/24,198.51.100.0/24,203.0.113.0/24
    planName: stackit-rabbitmq-1.2.10-replica
    projectId: <PROJECT-ID>
    version: "3.13"
