apiVersion: serviceaccount.stackit.crossplane.io/v1alpha1
kind: Account
metadata:
  labels:
    testing.upbound.io/example-name: example-sa
  name: example-sa
spec:
  forProvider:
    name: example-service-account
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  providerConfigRef:
    name: default
