apiVersion: kms.stackit.m.crossplane.io/v1alpha1
kind: Keyring
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/keyring
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    description: example description
    displayName: example-name
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
