apiVersion: edgecloud.stackit.crossplane.io/v1alpha1
kind: Kubeconfig
metadata:
  annotations:
    meta.upbound.io/example-id: edgecloud/v1alpha1/kubeconfig
  labels:
    testing.upbound.io/example-name: by_name
  name: by-name
spec:
  forProvider:
    expiration: 3600
    instanceName: ${stackit_edgecloud_instance.this.display_name}
    projectId: ${var.project_id}

---

apiVersion: edgecloud.stackit.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: edgecloud/v1alpha1/kubeconfig
  labels:
    testing.upbound.io/example-name: this
  name: this
spec:
  forProvider:
    description: some_description
    displayName: example
    planId: ${var.plan_id}
    projectId: ${local.project_id}
