apiVersion: ske.stackit.m.crossplane.io/v1alpha1
kind: Kubeconfig
metadata:
  annotations:
    meta.upbound.io/example-id: ske/v1alpha1/kubeconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    expiration: 7200
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    refresh: true
    refreshBefore: 3600
