apiVersion: observability.stackit.crossplane.io/v1alpha1
kind: Scrapeconfig
metadata:
  annotations:
    meta.upbound.io/example-id: observability/v1alpha1/scrapeconfig
  labels:
    testing.upbound.io/example-name: example-scrapeconfig
  name: example-scrapeconfig
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-observability
    metricsPath: /my-metrics
    name: example-job
    projectId: <PROJECT-ID>
    saml2:
      enableUrlParameters: true
    targets:
    - labels:
        url1: dev
      urls:
      - url1
      - urls2
