apiVersion: observability.stackit.crossplane.io/v1alpha1
kind: Credential
metadata:
  annotations:
    meta.upbound.io/example-id: observability/v1alpha1/credential
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    description: Description of the credential.
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
