// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type AccountAccessTokenInitParameters struct {

	// (String) STACKIT project ID associated with the service account token.
	// STACKIT project ID associated with the service account token.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Map of String) A map of arbitrary key/value pairs that will force recreation of the token when they change, enabling token rotation based on external conditions such as a rotating timestamp. Changing this forces a new resource to be created.
	// A map of arbitrary key/value pairs that will force recreation of the token when they change, enabling token rotation based on external conditions such as a rotating timestamp. Changing this forces a new resource to be created.
	// +mapType=granular
	RotateWhenChanged map[string]*string `json:"rotateWhenChanged,omitempty" tf:"rotate_when_changed,omitempty"`

	// (String) Email address linked to the service account.
	// Email address linked to the service account.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/namespaced/serviceaccount/v1alpha1.Account
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("email",true)
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty" tf:"service_account_email,omitempty"`

	// Reference to a Account in serviceaccount to populate serviceAccountEmail.
	// +kubebuilder:validation:Optional
	ServiceAccountEmailRef *v1.NamespacedReference `json:"serviceAccountEmailRef,omitempty" tf:"-"`

	// Selector for a Account in serviceaccount to populate serviceAccountEmail.
	// +kubebuilder:validation:Optional
	ServiceAccountEmailSelector *v1.NamespacedSelector `json:"serviceAccountEmailSelector,omitempty" tf:"-"`

	// (Number) Specifies the token's validity duration in days. If unspecified, defaults to 90 days.
	// Specifies the token's validity duration in days. If unspecified, defaults to 90 days.
	TTLDays *float64 `json:"ttlDays,omitempty" tf:"ttl_days,omitempty"`
}

type AccountAccessTokenObservation struct {

	// (String) Identifier for the access token linked to the service account.
	// Identifier for the access token linked to the service account.
	AccessTokenID *string `json:"accessTokenId,omitempty" tf:"access_token_id,omitempty"`

	// (Boolean) Indicate whether the token is currently active or inactive
	// Indicate whether the token is currently active or inactive
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// (String) Timestamp indicating when the access token was created.
	// Timestamp indicating when the access token was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// It is structured as "project_id,service_account_email,access_token_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) STACKIT project ID associated with the service account token.
	// STACKIT project ID associated with the service account token.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Map of String) A map of arbitrary key/value pairs that will force recreation of the token when they change, enabling token rotation based on external conditions such as a rotating timestamp. Changing this forces a new resource to be created.
	// A map of arbitrary key/value pairs that will force recreation of the token when they change, enabling token rotation based on external conditions such as a rotating timestamp. Changing this forces a new resource to be created.
	// +mapType=granular
	RotateWhenChanged map[string]*string `json:"rotateWhenChanged,omitempty" tf:"rotate_when_changed,omitempty"`

	// (String) Email address linked to the service account.
	// Email address linked to the service account.
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty" tf:"service_account_email,omitempty"`

	// (Number) Specifies the token's validity duration in days. If unspecified, defaults to 90 days.
	// Specifies the token's validity duration in days. If unspecified, defaults to 90 days.
	TTLDays *float64 `json:"ttlDays,omitempty" tf:"ttl_days,omitempty"`

	// (String) Estimated expiration timestamp of the access token. For precise validity, check the JWT details.
	// Estimated expiration timestamp of the access token. For precise validity, check the JWT details.
	ValidUntil *string `json:"validUntil,omitempty" tf:"valid_until,omitempty"`
}

type AccountAccessTokenParameters struct {

	// (String) STACKIT project ID associated with the service account token.
	// STACKIT project ID associated with the service account token.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Map of String) A map of arbitrary key/value pairs that will force recreation of the token when they change, enabling token rotation based on external conditions such as a rotating timestamp. Changing this forces a new resource to be created.
	// A map of arbitrary key/value pairs that will force recreation of the token when they change, enabling token rotation based on external conditions such as a rotating timestamp. Changing this forces a new resource to be created.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	RotateWhenChanged map[string]*string `json:"rotateWhenChanged,omitempty" tf:"rotate_when_changed,omitempty"`

	// (String) Email address linked to the service account.
	// Email address linked to the service account.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/namespaced/serviceaccount/v1alpha1.Account
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("email",true)
	// +kubebuilder:validation:Optional
	ServiceAccountEmail *string `json:"serviceAccountEmail,omitempty" tf:"service_account_email,omitempty"`

	// Reference to a Account in serviceaccount to populate serviceAccountEmail.
	// +kubebuilder:validation:Optional
	ServiceAccountEmailRef *v1.NamespacedReference `json:"serviceAccountEmailRef,omitempty" tf:"-"`

	// Selector for a Account in serviceaccount to populate serviceAccountEmail.
	// +kubebuilder:validation:Optional
	ServiceAccountEmailSelector *v1.NamespacedSelector `json:"serviceAccountEmailSelector,omitempty" tf:"-"`

	// (Number) Specifies the token's validity duration in days. If unspecified, defaults to 90 days.
	// Specifies the token's validity duration in days. If unspecified, defaults to 90 days.
	// +kubebuilder:validation:Optional
	TTLDays *float64 `json:"ttlDays,omitempty" tf:"ttl_days,omitempty"`
}

// AccountAccessTokenSpec defines the desired state of AccountAccessToken
type AccountAccessTokenSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            AccountAccessTokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccountAccessTokenInitParameters `json:"initProvider,omitempty"`
}

// AccountAccessTokenStatus defines the observed state of AccountAccessToken.
type AccountAccessTokenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccountAccessTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccountAccessToken is the Schema for the AccountAccessTokens API. Service account access token schema. !> This resource is scheduled for deprecation and will be removed on December 17, 2025. To ensure a smooth transition, please refer to our migration guide at https://docs.stackit.cloud/platform/access-and-identity/service-accounts/migrate-flows/ for detailed instructions and recommendations. Example Usage Automatically rotate access tokens
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,stackit}
type AccountAccessToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   AccountAccessTokenSpec   `json:"spec"`
	Status AccountAccessTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccountAccessTokenList contains a list of AccountAccessTokens
type AccountAccessTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccountAccessToken `json:"items"`
}

// Repository type metadata.
var (
	AccountAccessToken_Kind             = "AccountAccessToken"
	AccountAccessToken_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccountAccessToken_Kind}.String()
	AccountAccessToken_KindAPIVersion   = AccountAccessToken_Kind + "." + CRDGroupVersion.String()
	AccountAccessToken_GroupVersionKind = CRDGroupVersion.WithKind(AccountAccessToken_Kind)
)

func init() {
	SchemeBuilder.Register(&AccountAccessToken{}, &AccountAccessTokenList{})
}
