apiVersion: observability.stackit.crossplane.io/v1alpha1
kind: Alertgroup
metadata:
  annotations:
    meta.upbound.io/example-id: observability/v1alpha1/alertgroup
  labels:
    testing.upbound.io/example-name: example-alertgroup
  name: example-alertgroup
spec:
  forProvider:
    projectId: <PROJECT-ID>
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-observability
    name: example-alert-group
    rules:
      - alert: HighCPU
        expression: cpu_usage > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: CPU usage is high
