apiVersion: observability.stackit.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: observability/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example-scrapeconfig
  name: example-scrapeconfig
spec:
  forProvider:
    name: example-instance
    planName: Observability-Monitoring-Starter-EU01
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
---
apiVersion: observability.stackit.crossplane.io/v1alpha1
kind: Scrapeconfig
metadata:
  annotations:
    meta.upbound.io/example-id: observability/v1alpha1/scrapeconfig
  labels:
    testing.upbound.io/example-name: example-scrapeconfig
  name: example-scrapeconfig
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-scrapeconfig
    metricsPath: /my-metrics
    name: example-job
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    saml2:
      enableUrlParameters: true
    targets:
    - labels:
        url1: dev
      urls:
      - url1
      - urls2
