apiVersion: secretsmanager.stackit.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: secretsmanager/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-instance
    projectId: 12345678-abcd-1234-abcd-123456789abc
  providerConfigRef:
    name: provider-stackit-config
