apiVersion: postgresflex.m.stackit.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: postgresflex/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: hello-crossplane
  name: hello-crossplane
spec:
  forProvider:
    acl:
    - 193.148.160.0/19
    - 45.129.40.0/21
    backupSchedule: 00 00 * * *
    flavor:
      cpu: 2
      ram: 4
    name: hello-crossplane
    projectId: 12345678-abcd-1234-abcd-123456789abc
    replicas: 1
    storage:
      class: premium-perf2-stackit
      size: 5
    version: "17"
  providerConfigRef:
    name: provider-stackit-config
