apiVersion: objectstorage.stackit.crossplane.io/v1alpha1
kind: Bucket
metadata:
  name: hello-crossplane
spec:
  forProvider:
    name: 04ce9fde-hello-crossplane
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
  providerConfigRef:
    name: default
