apiVersion: kms.stackit.crossplane.io/v1alpha1
kind: WrappingKey
metadata:
  annotations:
    meta.upbound.io/example-id: kms/v1alpha1/wrappingkey
  labels:
    testing.upbound.io/example-name: example-wrapping-key
  name: example-wrapping-key
spec:
  forProvider:
    displayName: example-wrapping-key
    algorithm: rsa_2048_oaep_sha256
    protection: software
    purpose: wrap_symmetric_key
    projectId: <PROJECT-ID>
    keyringIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-keyring
