apiVersion: authorization.stackit.crossplane.io/v1alpha1
kind: OrganizationRoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1alpha1/organizationroleassignment
  labels:
    testing.upbound.io/example-name: example-org-role
  name: example-org-role
spec:
  forProvider:
    resourceId: <ORGANIZATION-ID>
    role: reader
    subject: <SA-EMAIL>
