apiVersion: authorization.stackit.crossplane.io/v1alpha1
kind: ProjectRoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: authorization/v1alpha1/projectroleassignment
  labels:
    testing.upbound.io/example-name: example-project-role
  name: example-project-role
spec:
  forProvider:
    resourceId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    role: reader
    subject: uptest-dpildner-n8ejt1i8@sa.stackit.cloud
