apiVersion: logme.stackit.crossplane.io/v1alpha1
kind: Credential
metadata:
  annotations:
    meta.upbound.io/example-id: logme/v1alpha1/credential
  labels:
    testing.upbound.io/example-name: example-logme-credential
  name: example-logme-credential
spec:
  forProvider:
    projectId: <PROJECT-ID>
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-logme
