apiVersion: objectstorage.stackit.crossplane.io/v1alpha1
kind: Bucket
metadata:
  annotations:
    meta.upbound.io/example-id: objectstorage/v1alpha1/bucket
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    name: example-bucket
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
