apiVersion: mongodbflex.stackit.crossplane.io/v1alpha1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: example-mongodbflex
  name: example-mongodbflex
spec:
  forProvider:
    name: example-mongodbflex
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    flavor:
      cpu: 2
      ram: 4
    storage:
      class: premium-perf2-stackit
      size: 10
    version: "7.0"
    replicas: 1
    backupSchedule: "0 0 * * *"
  providerConfigRef:
    name: default
