apiVersion: mongodbflex.stackit.crossplane.io/v1alpha1
kind: User
metadata:
  labels:
    testing.upbound.io/example-name: example-mongodbflex-user
  name: example-mongodbflex-user
spec:
  forProvider:
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-mongodbflex
    username: example-user
    roles:
      - readWrite
    database: example-db
  providerConfigRef:
    name: default
