apiVersion: mongodbflex.stackit.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: mongodbflex/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example-mongodbflex-user
  name: example-mongodbflex-user
spec:
  forProvider:
    projectId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-mongodbflex
    username: example-user
    roles:
      - readWrite
    database: example-db
