apiVersion: sqlserverflex.stackit.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: sqlserverflex/v1alpha1/user
  labels:
    testing.upbound.io/example-name: example-sqlserverflex-user
  name: example-sqlserverflex-user
spec:
  forProvider:
    projectId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-sqlserverflex
    username: example-user
    roles:
      - "##STACKIT_LoginManager##"
