apiVersion: dns.stackit.crossplane.io/v1alpha1
kind: RecordSet
metadata:
  labels:
    testing.upbound.io/example-name: example-recordset
  name: example-recordset
spec:
  forProvider:
    name: www
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    type: A
    records:
      - 1.2.3.4
    ttl: 300
    zoneIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-zone
  providerConfigRef:
    name: default
