apiVersion: redis.stackit.crossplane.io/v1alpha1
kind: ClusterCredential
metadata:
  annotations:
    meta.upbound.io/example-id: redis/v1alpha1/clustercredential
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
