apiVersion: opensearch.stackit.crossplane.io/v1alpha1
kind: Credential
metadata:
  annotations:
    meta.upbound.io/example-id: opensearch/v1alpha1/credential
  labels:
    testing.upbound.io/example-name: example-opensearch-credential
  name: example-opensearch-credential
spec:
  forProvider:
    projectId: <PROJECT-ID>
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-opensearch
