apiVersion: observability.stackit.m.crossplane.io/v1alpha1
kind: Scrapeconfig
metadata:
  annotations:
    meta.upbound.io/example-id: observability/v1alpha1/scrapeconfig
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    instanceIdRef:
      name: example
    metricsPath: /my-metrics
    name: example-job
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    saml2:
      enableUrlParameters: true
    targets:
    - labels:
        url1: dev
      urls:
      - url1
      - urls2
