// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ShareInitParameters struct {

	// (String) Name of the Share Export Policy to use in the Share.
	// Note that if this is set to an empty string, the Share can only be mounted in read only by
	// clients with IPs matching the IP ACL of the Resource Pool hosting this Share.
	// You can also assign a Share Export Policy after creating the Share
	// Name of the Share Export Policy to use in the Share.
	// Note that if this is set to an empty string, the Share can only be mounted in read only by
	// clients with IPs matching the IP ACL of the Resource Pool hosting this Share.
	// You can also assign a Share Export Policy after creating the Share
	ExportPolicy *string `json:"exportPolicy,omitempty" tf:"export_policy,omitempty"`

	// (String) Name of the share.
	// Name of the share.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the share is associated.
	// STACKIT project ID to which the share is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of the resource pool for the SFS share.
	// The ID of the resource pool for the SFS share.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/namespaced/sfs/v1alpha1.ResourcePool
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("resource_pool_id",true)
	ResourcePoolID *string `json:"resourcePoolId,omitempty" tf:"resource_pool_id,omitempty"`

	// Reference to a ResourcePool in sfs to populate resourcePoolId.
	// +kubebuilder:validation:Optional
	ResourcePoolIDRef *v1.NamespacedReference `json:"resourcePoolIdRef,omitempty" tf:"-"`

	// Selector for a ResourcePool in sfs to populate resourcePoolId.
	// +kubebuilder:validation:Optional
	ResourcePoolIDSelector *v1.NamespacedSelector `json:"resourcePoolIdSelector,omitempty" tf:"-"`

	// (Number) Space hard limit for the Share.
	// If zero, the Share will have access to the full space of the Resource Pool it lives in.
	// (unit: gigabytes)
	// Space hard limit for the Share.
	// If zero, the Share will have access to the full space of the Resource Pool it lives in.
	// (unit: gigabytes)
	SpaceHardLimitGigabytes *float64 `json:"spaceHardLimitGigabytes,omitempty" tf:"space_hard_limit_gigabytes,omitempty"`
}

type ShareObservation struct {

	// (String) Name of the Share Export Policy to use in the Share.
	// Note that if this is set to an empty string, the Share can only be mounted in read only by
	// clients with IPs matching the IP ACL of the Resource Pool hosting this Share.
	// You can also assign a Share Export Policy after creating the Share
	// Name of the Share Export Policy to use in the Share.
	// Note that if this is set to an empty string, the Share can only be mounted in read only by
	// clients with IPs matching the IP ACL of the Resource Pool hosting this Share.
	// You can also assign a Share Export Policy after creating the Share
	ExportPolicy *string `json:"exportPolicy,omitempty" tf:"export_policy,omitempty"`

	// It is structured as "project_id,region,resource_pool_id,share_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Mount path of the Share, used to mount the Share
	// Mount path of the Share, used to mount the Share
	MountPath *string `json:"mountPath,omitempty" tf:"mount_path,omitempty"`

	// (String) Name of the share.
	// Name of the share.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the share is associated.
	// STACKIT project ID to which the share is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of the resource pool for the SFS share.
	// The ID of the resource pool for the SFS share.
	ResourcePoolID *string `json:"resourcePoolId,omitempty" tf:"resource_pool_id,omitempty"`

	// (String) share ID
	// share ID
	ShareID *string `json:"shareId,omitempty" tf:"share_id,omitempty"`

	// (Number) Space hard limit for the Share.
	// If zero, the Share will have access to the full space of the Resource Pool it lives in.
	// (unit: gigabytes)
	// Space hard limit for the Share.
	// If zero, the Share will have access to the full space of the Resource Pool it lives in.
	// (unit: gigabytes)
	SpaceHardLimitGigabytes *float64 `json:"spaceHardLimitGigabytes,omitempty" tf:"space_hard_limit_gigabytes,omitempty"`
}

type ShareParameters struct {

	// (String) Name of the Share Export Policy to use in the Share.
	// Note that if this is set to an empty string, the Share can only be mounted in read only by
	// clients with IPs matching the IP ACL of the Resource Pool hosting this Share.
	// You can also assign a Share Export Policy after creating the Share
	// Name of the Share Export Policy to use in the Share.
	// Note that if this is set to an empty string, the Share can only be mounted in read only by
	// clients with IPs matching the IP ACL of the Resource Pool hosting this Share.
	// You can also assign a Share Export Policy after creating the Share
	// +kubebuilder:validation:Optional
	ExportPolicy *string `json:"exportPolicy,omitempty" tf:"export_policy,omitempty"`

	// (String) Name of the share.
	// Name of the share.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the share is associated.
	// STACKIT project ID to which the share is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The ID of the resource pool for the SFS share.
	// The ID of the resource pool for the SFS share.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/namespaced/sfs/v1alpha1.ResourcePool
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("resource_pool_id",true)
	// +kubebuilder:validation:Optional
	ResourcePoolID *string `json:"resourcePoolId,omitempty" tf:"resource_pool_id,omitempty"`

	// Reference to a ResourcePool in sfs to populate resourcePoolId.
	// +kubebuilder:validation:Optional
	ResourcePoolIDRef *v1.NamespacedReference `json:"resourcePoolIdRef,omitempty" tf:"-"`

	// Selector for a ResourcePool in sfs to populate resourcePoolId.
	// +kubebuilder:validation:Optional
	ResourcePoolIDSelector *v1.NamespacedSelector `json:"resourcePoolIdSelector,omitempty" tf:"-"`

	// (Number) Space hard limit for the Share.
	// If zero, the Share will have access to the full space of the Resource Pool it lives in.
	// (unit: gigabytes)
	// Space hard limit for the Share.
	// If zero, the Share will have access to the full space of the Resource Pool it lives in.
	// (unit: gigabytes)
	// +kubebuilder:validation:Optional
	SpaceHardLimitGigabytes *float64 `json:"spaceHardLimitGigabytes,omitempty" tf:"space_hard_limit_gigabytes,omitempty"`
}

// ShareSpec defines the desired state of Share
type ShareSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ShareParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ShareInitParameters `json:"initProvider,omitempty"`
}

// ShareStatus defines the observed state of Share.
type ShareStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ShareObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Share is the Schema for the Shares API. SFS Share schema. Must have a region specified in the provider configuration. ~> This resource is in beta and may be subject to breaking changes in the future. Use with caution. See our guide https://registry.io/providers/stackitcloud/stackit/latest/docs/guides/opting_into_beta_resources for how to opt-in to use beta resources.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,stackit}
type Share struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.exportPolicy) || (has(self.initProvider) && has(self.initProvider.exportPolicy))",message="spec.forProvider.exportPolicy is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.spaceHardLimitGigabytes) || (has(self.initProvider) && has(self.initProvider.spaceHardLimitGigabytes))",message="spec.forProvider.spaceHardLimitGigabytes is a required parameter"
	Spec   ShareSpec   `json:"spec"`
	Status ShareStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ShareList contains a list of Shares
type ShareList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Share `json:"items"`
}

// Repository type metadata.
var (
	Share_Kind             = "Share"
	Share_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Share_Kind}.String()
	Share_KindAPIVersion   = Share_Kind + "." + CRDGroupVersion.String()
	Share_GroupVersionKind = CRDGroupVersion.WithKind(Share_Kind)
)

func init() {
	SchemeBuilder.Register(&Share{}, &ShareList{})
}
