apiVersion: ske.stackit.crossplane.io/v1alpha1
kind: Cluster
metadata:
  labels:
    testing.upbound.io/example-name: example-cluster
  name: example-cluster
spec:
  forProvider:
    name: example-cluster
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    kubernetesVersionMin: "1.29"
    nodePools:
      - name: pool-1
        machineType: g1.2
        minimum: 1
        maximum: 3
        availabilityZones:
          - eu01-1
        os:
          name: flatcar
          version: "3815.2.0"
        cri:
          name: containerd
  providerConfigRef:
    name: default
