apiVersion: ske.stackit.crossplane.io/v1alpha1
kind: Kubeconfig
metadata:
  labels:
    testing.upbound.io/example-name: example-kubeconfig
  name: example-kubeconfig
spec:
  forProvider:
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    clusterName: example-cluster
    expiration: "3600s"
    refresh: true
  providerConfigRef:
    name: default
