apiVersion: ske.stackit.crossplane.io/v1alpha1
kind: Kubeconfig
metadata:
  annotations:
    meta.upbound.io/example-id: ske/v1alpha1/kubeconfig
  labels:
    testing.upbound.io/example-name: example-kubeconfig
  name: example-kubeconfig
spec:
  forProvider:
    projectId: <PROJECT-ID>
    clusterNameSelector:
      matchLabels:
        testing.upbound.io/example-name: example-cluster
    expiration: 3600
    refresh: true
