apiVersion: mariadb.stackit.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: mariadb/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example-mariadb
  name: example-mariadb
spec:
  forProvider:
    name: example-mariadb
    projectId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    planName: stackit-mariadb-1.4.10-single
    version: "10.6"
