// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type FolderInitParameters struct {

	// value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// Labels are key-value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the folder.
	// The name of the folder.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Email address of the owner of the folder. This value is only considered during creation. Changing it afterwards will have no effect.
	// Email address of the owner of the folder. This value is only considered during creation. Changing it afterwards will have no effect.
	OwnerEmail *string `json:"ownerEmail,omitempty" tf:"owner_email,omitempty"`

	// friendly) and UUID are supported.
	// Parent resource identifier. Both container ID (user-friendly) and UUID are supported.
	ParentContainerID *string `json:"parentContainerId,omitempty" tf:"parent_container_id,omitempty"`
}

type FolderObservation struct {

	// friendly identifier.
	// Folder container ID. Globally unique, user-friendly identifier.
	ContainerID *string `json:"containerId,omitempty" tf:"container_id,omitempty"`

	// time at which the folder was created.
	// Date-time at which the folder was created.
	CreationTime *string `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// (String) Folder UUID identifier. Globally unique folder identifier
	// Folder UUID identifier. Globally unique folder identifier
	FolderID *string `json:"folderId,omitempty" tf:"folder_id,omitempty"`

	// It is structured as "container_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// Labels are key-value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the folder.
	// The name of the folder.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Email address of the owner of the folder. This value is only considered during creation. Changing it afterwards will have no effect.
	// Email address of the owner of the folder. This value is only considered during creation. Changing it afterwards will have no effect.
	OwnerEmail *string `json:"ownerEmail,omitempty" tf:"owner_email,omitempty"`

	// friendly) and UUID are supported.
	// Parent resource identifier. Both container ID (user-friendly) and UUID are supported.
	ParentContainerID *string `json:"parentContainerId,omitempty" tf:"parent_container_id,omitempty"`

	// time at which the folder was last modified.
	// Date-time at which the folder was last modified.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type FolderParameters struct {

	// value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// Labels are key-value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the folder.
	// The name of the folder.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Email address of the owner of the folder. This value is only considered during creation. Changing it afterwards will have no effect.
	// Email address of the owner of the folder. This value is only considered during creation. Changing it afterwards will have no effect.
	// +kubebuilder:validation:Optional
	OwnerEmail *string `json:"ownerEmail,omitempty" tf:"owner_email,omitempty"`

	// friendly) and UUID are supported.
	// Parent resource identifier. Both container ID (user-friendly) and UUID are supported.
	// +kubebuilder:validation:Optional
	ParentContainerID *string `json:"parentContainerId,omitempty" tf:"parent_container_id,omitempty"`
}

// FolderSpec defines the desired state of Folder
type FolderSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     FolderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FolderInitParameters `json:"initProvider,omitempty"`
}

// FolderStatus defines the observed state of Folder.
type FolderStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FolderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Folder is the Schema for the Folders API. Resource Manager folder resource schema.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type Folder struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ownerEmail) || (has(self.initProvider) && has(self.initProvider.ownerEmail))",message="spec.forProvider.ownerEmail is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parentContainerId) || (has(self.initProvider) && has(self.initProvider.parentContainerId))",message="spec.forProvider.parentContainerId is a required parameter"
	Spec   FolderSpec   `json:"spec"`
	Status FolderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FolderList contains a list of Folders
type FolderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Folder `json:"items"`
}

// Repository type metadata.
var (
	Folder_Kind             = "Folder"
	Folder_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Folder_Kind}.String()
	Folder_KindAPIVersion   = Folder_Kind + "." + CRDGroupVersion.String()
	Folder_GroupVersionKind = CRDGroupVersion.WithKind(Folder_Kind)
)

func init() {
	SchemeBuilder.Register(&Folder{}, &FolderList{})
}
