apiVersion: network.stackit.crossplane.io/v1alpha1
kind: NetworkInterfaceAttach
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/networkinterfaceattach
  labels:
    testing.upbound.io/example-name: attached_network_interface
  name: attached-network-interface
spec:
  forProvider:
    networkInterfaceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    serverId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
