apiVersion: secretsmanager.stackit.crossplane.io/v1alpha1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: secretsmanager/v1alpha1/instance
  labels:
    testing.upbound.io/example-name: example-secretsmanager
  name: example-secretsmanager
spec:
  forProvider:
    name: example-secretsmanager
    projectId: <PROJECT-ID>
