apiVersion: serviceaccount.stackit.crossplane.io/v1alpha1
kind: AccountAccessToken
metadata:
  annotations:
    meta.upbound.io/example-id: serviceaccount/v1alpha1/accountaccesstoken
  labels:
    testing.upbound.io/example-name: sa_token
  name: sa-token
spec:
  forProvider:
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    rotateWhenChanged:
      rotation: ${time_rotating.rotate.id}
    serviceAccountEmailSelector:
      matchLabels:
        testing.upbound.io/example-name: sa
    ttlDays: 180

---

apiVersion: serviceaccount.stackit.crossplane.io/v1alpha1
kind: Account
metadata:
  annotations:
    meta.upbound.io/example-id: serviceaccount/v1alpha1/accountaccesstoken
  labels:
    testing.upbound.io/example-name: sa
  name: sa
spec:
  forProvider:
    name: sa01
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
