apiVersion: network.stackit.m.crossplane.io/v1alpha1
kind: AreaRoute
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/arearoute
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    destination:
      type: cidrv4
      value: 192.168.0.0/24
    labels:
      key: value
    networkAreaIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    nextHop:
      type: ipv4
      value: 192.168.0.0
    organizationId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
