apiVersion: network.stackit.m.crossplane.io/v1alpha1
kind: NetworkInterface
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1alpha1/networkinterface
  labels:
    testing.upbound.io/example-name: example
  name: example
  namespace: crossplane-system
spec:
  forProvider:
    allowedAddresses:
    - 192.168.0.0/24
    networkIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    securityGroupIds:
    - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
