// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AreaRegionInitParameters struct {

	// (Attributes) The regional IPv4 config of a network area. (see below for nested schema)
	IPv4 *IPv4InitParameters `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (String) The network area ID.
	// The network area ID.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/network/v1alpha1.Area
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("network_area_id",true)
	NetworkAreaID *string `json:"networkAreaId,omitempty" tf:"network_area_id,omitempty"`

	// Reference to a Area in network to populate networkAreaId.
	// +kubebuilder:validation:Optional
	NetworkAreaIDRef *v1.Reference `json:"networkAreaIdRef,omitempty" tf:"-"`

	// Selector for a Area in network to populate networkAreaId.
	// +kubebuilder:validation:Optional
	NetworkAreaIDSelector *v1.Selector `json:"networkAreaIdSelector,omitempty" tf:"-"`

	// (String) STACKIT organization ID to which the network area is associated.
	// STACKIT organization ID to which the network area is associated.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type AreaRegionObservation struct {

	// It is structured as "organization_id,network_area_id,region".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) The regional IPv4 config of a network area. (see below for nested schema)
	IPv4 *IPv4Observation `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (String) The network area ID.
	// The network area ID.
	NetworkAreaID *string `json:"networkAreaId,omitempty" tf:"network_area_id,omitempty"`

	// (String) STACKIT organization ID to which the network area is associated.
	// STACKIT organization ID to which the network area is associated.
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type AreaRegionParameters struct {

	// (Attributes) The regional IPv4 config of a network area. (see below for nested schema)
	// +kubebuilder:validation:Optional
	IPv4 *IPv4Parameters `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// (String) The network area ID.
	// The network area ID.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/network/v1alpha1.Area
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("network_area_id",true)
	// +kubebuilder:validation:Optional
	NetworkAreaID *string `json:"networkAreaId,omitempty" tf:"network_area_id,omitempty"`

	// Reference to a Area in network to populate networkAreaId.
	// +kubebuilder:validation:Optional
	NetworkAreaIDRef *v1.Reference `json:"networkAreaIdRef,omitempty" tf:"-"`

	// Selector for a Area in network to populate networkAreaId.
	// +kubebuilder:validation:Optional
	NetworkAreaIDSelector *v1.Selector `json:"networkAreaIdSelector,omitempty" tf:"-"`

	// (String) STACKIT organization ID to which the network area is associated.
	// STACKIT organization ID to which the network area is associated.
	// +kubebuilder:validation:Optional
	OrganizationID *string `json:"organizationId,omitempty" tf:"organization_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type IPv4InitParameters struct {

	// (List of String) List of DNS Servers/Nameservers.
	// List of DNS Servers/Nameservers.
	DefaultNameservers []*string `json:"defaultNameservers,omitempty" tf:"default_nameservers,omitempty"`

	// (Number) The default prefix length for networks in the network area.
	// The default prefix length for networks in the network area.
	DefaultPrefixLength *float64 `json:"defaultPrefixLength,omitempty" tf:"default_prefix_length,omitempty"`

	// (Number) The maximal prefix length for networks in the network area.
	// The maximal prefix length for networks in the network area.
	MaxPrefixLength *float64 `json:"maxPrefixLength,omitempty" tf:"max_prefix_length,omitempty"`

	// (Number) The minimal prefix length for networks in the network area.
	// The minimal prefix length for networks in the network area.
	MinPrefixLength *float64 `json:"minPrefixLength,omitempty" tf:"min_prefix_length,omitempty"`

	// (Attributes List) List of Network ranges. (see below for nested schema)
	NetworkRanges []IPv4NetworkRangesInitParameters `json:"networkRanges,omitempty" tf:"network_ranges,omitempty"`

	// Domain Routing (CIDR).
	// IPv4 Classless Inter-Domain Routing (CIDR).
	TransferNetwork *string `json:"transferNetwork,omitempty" tf:"transfer_network,omitempty"`
}

type IPv4NetworkRangesInitParameters struct {

	// Domain Routing (CIDR).
	// Classless Inter-Domain Routing (CIDR).
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type IPv4NetworkRangesObservation struct {

	// (String)
	NetworkRangeID *string `json:"networkRangeId,omitempty" tf:"network_range_id,omitempty"`

	// Domain Routing (CIDR).
	// Classless Inter-Domain Routing (CIDR).
	Prefix *string `json:"prefix,omitempty" tf:"prefix,omitempty"`
}

type IPv4NetworkRangesParameters struct {

	// Domain Routing (CIDR).
	// Classless Inter-Domain Routing (CIDR).
	// +kubebuilder:validation:Optional
	Prefix *string `json:"prefix" tf:"prefix,omitempty"`
}

type IPv4Observation struct {

	// (List of String) List of DNS Servers/Nameservers.
	// List of DNS Servers/Nameservers.
	DefaultNameservers []*string `json:"defaultNameservers,omitempty" tf:"default_nameservers,omitempty"`

	// (Number) The default prefix length for networks in the network area.
	// The default prefix length for networks in the network area.
	DefaultPrefixLength *float64 `json:"defaultPrefixLength,omitempty" tf:"default_prefix_length,omitempty"`

	// (Number) The maximal prefix length for networks in the network area.
	// The maximal prefix length for networks in the network area.
	MaxPrefixLength *float64 `json:"maxPrefixLength,omitempty" tf:"max_prefix_length,omitempty"`

	// (Number) The minimal prefix length for networks in the network area.
	// The minimal prefix length for networks in the network area.
	MinPrefixLength *float64 `json:"minPrefixLength,omitempty" tf:"min_prefix_length,omitempty"`

	// (Attributes List) List of Network ranges. (see below for nested schema)
	NetworkRanges []IPv4NetworkRangesObservation `json:"networkRanges,omitempty" tf:"network_ranges,omitempty"`

	// Domain Routing (CIDR).
	// IPv4 Classless Inter-Domain Routing (CIDR).
	TransferNetwork *string `json:"transferNetwork,omitempty" tf:"transfer_network,omitempty"`
}

type IPv4Parameters struct {

	// (List of String) List of DNS Servers/Nameservers.
	// List of DNS Servers/Nameservers.
	// +kubebuilder:validation:Optional
	DefaultNameservers []*string `json:"defaultNameservers,omitempty" tf:"default_nameservers,omitempty"`

	// (Number) The default prefix length for networks in the network area.
	// The default prefix length for networks in the network area.
	// +kubebuilder:validation:Optional
	DefaultPrefixLength *float64 `json:"defaultPrefixLength,omitempty" tf:"default_prefix_length,omitempty"`

	// (Number) The maximal prefix length for networks in the network area.
	// The maximal prefix length for networks in the network area.
	// +kubebuilder:validation:Optional
	MaxPrefixLength *float64 `json:"maxPrefixLength,omitempty" tf:"max_prefix_length,omitempty"`

	// (Number) The minimal prefix length for networks in the network area.
	// The minimal prefix length for networks in the network area.
	// +kubebuilder:validation:Optional
	MinPrefixLength *float64 `json:"minPrefixLength,omitempty" tf:"min_prefix_length,omitempty"`

	// (Attributes List) List of Network ranges. (see below for nested schema)
	// +kubebuilder:validation:Optional
	NetworkRanges []IPv4NetworkRangesParameters `json:"networkRanges" tf:"network_ranges,omitempty"`

	// Domain Routing (CIDR).
	// IPv4 Classless Inter-Domain Routing (CIDR).
	// +kubebuilder:validation:Optional
	TransferNetwork *string `json:"transferNetwork" tf:"transfer_network,omitempty"`
}

// AreaRegionSpec defines the desired state of AreaRegion
type AreaRegionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AreaRegionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AreaRegionInitParameters `json:"initProvider,omitempty"`
}

// AreaRegionStatus defines the observed state of AreaRegion.
type AreaRegionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AreaRegionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AreaRegion is the Schema for the AreaRegions API. Network area region resource schema.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type AreaRegion struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ipv4) || (has(self.initProvider) && has(self.initProvider.ipv4))",message="spec.forProvider.ipv4 is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.organizationId) || (has(self.initProvider) && has(self.initProvider.organizationId))",message="spec.forProvider.organizationId is a required parameter"
	Spec   AreaRegionSpec   `json:"spec"`
	Status AreaRegionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AreaRegionList contains a list of AreaRegions
type AreaRegionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AreaRegion `json:"items"`
}

// Repository type metadata.
var (
	AreaRegion_Kind             = "AreaRegion"
	AreaRegion_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AreaRegion_Kind}.String()
	AreaRegion_KindAPIVersion   = AreaRegion_Kind + "." + CRDGroupVersion.String()
	AreaRegion_GroupVersionKind = CRDGroupVersion.WithKind(AreaRegion_Kind)
)

func init() {
	SchemeBuilder.Register(&AreaRegion{}, &AreaRegionList{})
}
