// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AreaRegion.
func (mg *AreaRegion) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkAreaID),
		Extract:      resource.ExtractParamPath("network_area_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkAreaIDRef,
		Selector:     mg.Spec.ForProvider.NetworkAreaIDSelector,
		To: reference.To{
			List:    &AreaList{},
			Managed: &Area{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkAreaID")
	}
	mg.Spec.ForProvider.NetworkAreaID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkAreaIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkAreaID),
		Extract:      resource.ExtractParamPath("network_area_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkAreaIDRef,
		Selector:     mg.Spec.InitProvider.NetworkAreaIDSelector,
		To: reference.To{
			List:    &AreaList{},
			Managed: &Area{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkAreaID")
	}
	mg.Spec.InitProvider.NetworkAreaID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkAreaIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AreaRoute.
func (mg *AreaRoute) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkAreaID),
		Extract:      resource.ExtractParamPath("network_area_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkAreaIDRef,
		Selector:     mg.Spec.ForProvider.NetworkAreaIDSelector,
		To: reference.To{
			List:    &AreaList{},
			Managed: &Area{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkAreaID")
	}
	mg.Spec.ForProvider.NetworkAreaID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkAreaIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkAreaID),
		Extract:      resource.ExtractParamPath("network_area_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkAreaIDRef,
		Selector:     mg.Spec.InitProvider.NetworkAreaIDSelector,
		To: reference.To{
			List:    &AreaList{},
			Managed: &Area{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkAreaID")
	}
	mg.Spec.InitProvider.NetworkAreaID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkAreaIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this GroupRule.
func (mg *GroupRule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SecurityGroupID),
		Extract:      resource.ExtractParamPath("security_group_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SecurityGroupIDRef,
		Selector:     mg.Spec.ForProvider.SecurityGroupIDSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SecurityGroupID")
	}
	mg.Spec.ForProvider.SecurityGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SecurityGroupIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SecurityGroupID),
		Extract:      resource.ExtractParamPath("security_group_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SecurityGroupIDRef,
		Selector:     mg.Spec.InitProvider.SecurityGroupIDSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SecurityGroupID")
	}
	mg.Spec.InitProvider.SecurityGroupID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SecurityGroupIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IP.
func (mg *IP) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkInterfaceID),
		Extract:      resource.ExtractParamPath("network_interface_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkInterfaceIDRef,
		Selector:     mg.Spec.ForProvider.NetworkInterfaceIDSelector,
		To: reference.To{
			List:    &NetworkInterfaceList{},
			Managed: &NetworkInterface{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkInterfaceID")
	}
	mg.Spec.ForProvider.NetworkInterfaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkInterfaceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkInterfaceID),
		Extract:      resource.ExtractParamPath("network_interface_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkInterfaceIDRef,
		Selector:     mg.Spec.InitProvider.NetworkInterfaceIDSelector,
		To: reference.To{
			List:    &NetworkInterfaceList{},
			Managed: &NetworkInterface{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkInterfaceID")
	}
	mg.Spec.InitProvider.NetworkInterfaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkInterfaceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this IPAssociate.
func (mg *IPAssociate) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkInterfaceID),
		Extract:      resource.ExtractParamPath("network_interface_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkInterfaceIDRef,
		Selector:     mg.Spec.ForProvider.NetworkInterfaceIDSelector,
		To: reference.To{
			List:    &NetworkInterfaceList{},
			Managed: &NetworkInterface{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkInterfaceID")
	}
	mg.Spec.ForProvider.NetworkInterfaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkInterfaceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PublicIPID),
		Extract:      resource.ExtractParamPath("public_ip_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PublicIPIDRef,
		Selector:     mg.Spec.ForProvider.PublicIPIDSelector,
		To: reference.To{
			List:    &IPList{},
			Managed: &IP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PublicIPID")
	}
	mg.Spec.ForProvider.PublicIPID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PublicIPIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkInterfaceID),
		Extract:      resource.ExtractParamPath("network_interface_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkInterfaceIDRef,
		Selector:     mg.Spec.InitProvider.NetworkInterfaceIDSelector,
		To: reference.To{
			List:    &NetworkInterfaceList{},
			Managed: &NetworkInterface{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkInterfaceID")
	}
	mg.Spec.InitProvider.NetworkInterfaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkInterfaceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PublicIPID),
		Extract:      resource.ExtractParamPath("public_ip_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PublicIPIDRef,
		Selector:     mg.Spec.InitProvider.PublicIPIDSelector,
		To: reference.To{
			List:    &IPList{},
			Managed: &IP{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PublicIPID")
	}
	mg.Spec.InitProvider.PublicIPID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PublicIPIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NetworkInterface.
func (mg *NetworkInterface) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkID),
		Extract:      resource.ExtractParamPath("network_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkIDRef,
		Selector:     mg.Spec.ForProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkID")
	}
	mg.Spec.ForProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkID),
		Extract:      resource.ExtractParamPath("network_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkIDRef,
		Selector:     mg.Spec.InitProvider.NetworkIDSelector,
		To: reference.To{
			List:    &NetworkList{},
			Managed: &Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkID")
	}
	mg.Spec.InitProvider.NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this NetworkInterfaceAttach.
func (mg *NetworkInterfaceAttach) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkInterfaceID),
		Extract:      resource.ExtractParamPath("network_interface_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkInterfaceIDRef,
		Selector:     mg.Spec.ForProvider.NetworkInterfaceIDSelector,
		To: reference.To{
			List:    &NetworkInterfaceList{},
			Managed: &NetworkInterface{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkInterfaceID")
	}
	mg.Spec.ForProvider.NetworkInterfaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkInterfaceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkInterfaceID),
		Extract:      resource.ExtractParamPath("network_interface_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkInterfaceIDRef,
		Selector:     mg.Spec.InitProvider.NetworkInterfaceIDSelector,
		To: reference.To{
			List:    &NetworkInterfaceList{},
			Managed: &NetworkInterface{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkInterfaceID")
	}
	mg.Spec.InitProvider.NetworkInterfaceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkInterfaceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Table.
func (mg *Table) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkAreaID),
		Extract:      resource.ExtractParamPath("network_area_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkAreaIDRef,
		Selector:     mg.Spec.ForProvider.NetworkAreaIDSelector,
		To: reference.To{
			List:    &AreaList{},
			Managed: &Area{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkAreaID")
	}
	mg.Spec.ForProvider.NetworkAreaID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkAreaIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkAreaID),
		Extract:      resource.ExtractParamPath("network_area_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkAreaIDRef,
		Selector:     mg.Spec.InitProvider.NetworkAreaIDSelector,
		To: reference.To{
			List:    &AreaList{},
			Managed: &Area{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkAreaID")
	}
	mg.Spec.InitProvider.NetworkAreaID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkAreaIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this TableRoute.
func (mg *TableRoute) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NetworkAreaID),
		Extract:      resource.ExtractParamPath("network_area_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NetworkAreaIDRef,
		Selector:     mg.Spec.ForProvider.NetworkAreaIDSelector,
		To: reference.To{
			List:    &AreaList{},
			Managed: &Area{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NetworkAreaID")
	}
	mg.Spec.ForProvider.NetworkAreaID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NetworkAreaIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RoutingTableID),
		Extract:      resource.ExtractParamPath("routing_table_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RoutingTableIDRef,
		Selector:     mg.Spec.ForProvider.RoutingTableIDSelector,
		To: reference.To{
			List:    &TableList{},
			Managed: &Table{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RoutingTableID")
	}
	mg.Spec.ForProvider.RoutingTableID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RoutingTableIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NetworkAreaID),
		Extract:      resource.ExtractParamPath("network_area_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NetworkAreaIDRef,
		Selector:     mg.Spec.InitProvider.NetworkAreaIDSelector,
		To: reference.To{
			List:    &AreaList{},
			Managed: &Area{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NetworkAreaID")
	}
	mg.Spec.InitProvider.NetworkAreaID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NetworkAreaIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RoutingTableID),
		Extract:      resource.ExtractParamPath("routing_table_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.RoutingTableIDRef,
		Selector:     mg.Spec.InitProvider.RoutingTableIDSelector,
		To: reference.To{
			List:    &TableList{},
			Managed: &Table{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RoutingTableID")
	}
	mg.Spec.InitProvider.RoutingTableID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RoutingTableIDRef = rsp.ResolvedReference

	return nil
}
