// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IPAssociateInitParameters struct {

	// (String) The ID of the network interface (or virtual IP) to which the public IP should be attached to.
	// The ID of the network interface (or virtual IP) to which the public IP should be attached to.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/network/v1alpha1.NetworkInterface
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("network_interface_id",true)
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`

	// Reference to a NetworkInterface in network to populate networkInterfaceId.
	// +kubebuilder:validation:Optional
	NetworkInterfaceIDRef *v1.Reference `json:"networkInterfaceIdRef,omitempty" tf:"-"`

	// Selector for a NetworkInterface in network to populate networkInterfaceId.
	// +kubebuilder:validation:Optional
	NetworkInterfaceIDSelector *v1.Selector `json:"networkInterfaceIdSelector,omitempty" tf:"-"`

	// (String) STACKIT project ID to which the public IP is associated.
	// STACKIT project ID to which the public IP is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The public IP ID.
	// The public IP ID.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/network/v1alpha1.IP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("public_ip_id",true)
	PublicIPID *string `json:"publicIpId,omitempty" tf:"public_ip_id,omitempty"`

	// Reference to a IP in network to populate publicIpId.
	// +kubebuilder:validation:Optional
	PublicIPIDRef *v1.Reference `json:"publicIpIdRef,omitempty" tf:"-"`

	// Selector for a IP in network to populate publicIpId.
	// +kubebuilder:validation:Optional
	PublicIPIDSelector *v1.Selector `json:"publicIpIdSelector,omitempty" tf:"-"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type IPAssociateObservation struct {

	// It is structured as "project_id,region,public_ip_id,network_interface_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The IP address.
	// The IP address.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// (String) The ID of the network interface (or virtual IP) to which the public IP should be attached to.
	// The ID of the network interface (or virtual IP) to which the public IP should be attached to.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`

	// (String) STACKIT project ID to which the public IP is associated.
	// STACKIT project ID to which the public IP is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The public IP ID.
	// The public IP ID.
	PublicIPID *string `json:"publicIpId,omitempty" tf:"public_ip_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type IPAssociateParameters struct {

	// (String) The ID of the network interface (or virtual IP) to which the public IP should be attached to.
	// The ID of the network interface (or virtual IP) to which the public IP should be attached to.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/network/v1alpha1.NetworkInterface
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("network_interface_id",true)
	// +kubebuilder:validation:Optional
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`

	// Reference to a NetworkInterface in network to populate networkInterfaceId.
	// +kubebuilder:validation:Optional
	NetworkInterfaceIDRef *v1.Reference `json:"networkInterfaceIdRef,omitempty" tf:"-"`

	// Selector for a NetworkInterface in network to populate networkInterfaceId.
	// +kubebuilder:validation:Optional
	NetworkInterfaceIDSelector *v1.Selector `json:"networkInterfaceIdSelector,omitempty" tf:"-"`

	// (String) STACKIT project ID to which the public IP is associated.
	// STACKIT project ID to which the public IP is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The public IP ID.
	// The public IP ID.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/network/v1alpha1.IP
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("public_ip_id",true)
	// +kubebuilder:validation:Optional
	PublicIPID *string `json:"publicIpId,omitempty" tf:"public_ip_id,omitempty"`

	// Reference to a IP in network to populate publicIpId.
	// +kubebuilder:validation:Optional
	PublicIPIDRef *v1.Reference `json:"publicIpIdRef,omitempty" tf:"-"`

	// Selector for a IP in network to populate publicIpId.
	// +kubebuilder:validation:Optional
	PublicIPIDSelector *v1.Selector `json:"publicIpIdSelector,omitempty" tf:"-"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// IPAssociateSpec defines the desired state of IPAssociate
type IPAssociateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IPAssociateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IPAssociateInitParameters `json:"initProvider,omitempty"`
}

// IPAssociateStatus defines the observed state of IPAssociate.
type IPAssociateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IPAssociateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// IPAssociate is the Schema for the IPAssociates API. Associates an existing public IP to a network interface. This is useful for situations where you have a pre-allocated public IP or unable to use the stackit_public_ip resource to create a new public IP. Must have a region specified in the provider configuration. !> The stackit_public_ip_associate resource should not be used together with the stackit_public_ip resource for the same public IP or for the same network interface. Using both resources together for the same public IP or network interface WILL lead to conflicts, as they both have control of the public IP and network interface association.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type IPAssociate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   IPAssociateSpec   `json:"spec"`
	Status IPAssociateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IPAssociateList contains a list of IPAssociates
type IPAssociateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []IPAssociate `json:"items"`
}

// Repository type metadata.
var (
	IPAssociate_Kind             = "IPAssociate"
	IPAssociate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: IPAssociate_Kind}.String()
	IPAssociate_KindAPIVersion   = IPAssociate_Kind + "." + CRDGroupVersion.String()
	IPAssociate_GroupVersionKind = CRDGroupVersion.WithKind(IPAssociate_Kind)
)

func init() {
	SchemeBuilder.Register(&IPAssociate{}, &IPAssociateList{})
}
