// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type NetworkInterfaceInitParameters struct {

	// Domain Routing) notations.
	// The list of CIDR (Classless Inter-Domain Routing) notations.
	AllowedAddresses []*string `json:"allowedAddresses,omitempty" tf:"allowed_addresses,omitempty"`

	// (String) The IPv4 address.
	// The IPv4 address.
	IPv4 *string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// value string pairs which can be attached to a network interface.
	// Labels are key-value string pairs which can be attached to a network interface.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the network interface.
	// The name of the network interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network ID to which the network interface is associated.
	// The network ID to which the network interface is associated.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/network/v1alpha1.Network
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("network_id",true)
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) STACKIT project ID to which the network is associated.
	// STACKIT project ID to which the network is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Boolean) The Network Interface Security. If set to false, then no security groups will apply to this network interface.
	// The Network Interface Security. If set to false, then no security groups will apply to this network interface.
	Security *bool `json:"security,omitempty" tf:"security,omitempty"`

	// (List of String) The list of security group UUIDs. If security is set to false, setting this field will lead to an error.
	// The list of security group UUIDs. If security is set to false, setting this field will lead to an error.
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`
}

type NetworkInterfaceObservation struct {

	// Domain Routing) notations.
	// The list of CIDR (Classless Inter-Domain Routing) notations.
	AllowedAddresses []*string `json:"allowedAddresses,omitempty" tf:"allowed_addresses,omitempty"`

	// (String) The device UUID of the network interface.
	// The device UUID of the network interface.
	Device *string `json:"device,omitempty" tf:"device,omitempty"`

	// It is structured as "project_id,region,network_id,network_interface_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The IPv4 address.
	// The IPv4 address.
	IPv4 *string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// value string pairs which can be attached to a network interface.
	// Labels are key-value string pairs which can be attached to a network interface.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The MAC address of network interface.
	// The MAC address of network interface.
	Mac *string `json:"mac,omitempty" tf:"mac,omitempty"`

	// (String) The name of the network interface.
	// The name of the network interface.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network ID to which the network interface is associated.
	// The network ID to which the network interface is associated.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// (String) The network interface ID.
	// The network interface ID.
	NetworkInterfaceID *string `json:"networkInterfaceId,omitempty" tf:"network_interface_id,omitempty"`

	// (String) STACKIT project ID to which the network is associated.
	// STACKIT project ID to which the network is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Boolean) The Network Interface Security. If set to false, then no security groups will apply to this network interface.
	// The Network Interface Security. If set to false, then no security groups will apply to this network interface.
	Security *bool `json:"security,omitempty" tf:"security,omitempty"`

	// (List of String) The list of security group UUIDs. If security is set to false, setting this field will lead to an error.
	// The list of security group UUIDs. If security is set to false, setting this field will lead to an error.
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`

	// (String) Type of network interface. Some of the possible values are: Possible values are: server, metadata, gateway.
	// Type of network interface. Some of the possible values are: Possible values are: `server`, `metadata`, `gateway`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type NetworkInterfaceParameters struct {

	// Domain Routing) notations.
	// The list of CIDR (Classless Inter-Domain Routing) notations.
	// +kubebuilder:validation:Optional
	AllowedAddresses []*string `json:"allowedAddresses,omitempty" tf:"allowed_addresses,omitempty"`

	// (String) The IPv4 address.
	// The IPv4 address.
	// +kubebuilder:validation:Optional
	IPv4 *string `json:"ipv4,omitempty" tf:"ipv4,omitempty"`

	// value string pairs which can be attached to a network interface.
	// Labels are key-value string pairs which can be attached to a network interface.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the network interface.
	// The name of the network interface.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The network ID to which the network interface is associated.
	// The network ID to which the network interface is associated.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/network/v1alpha1.Network
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("network_id",true)
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.Reference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.Selector `json:"networkIdSelector,omitempty" tf:"-"`

	// (String) STACKIT project ID to which the network is associated.
	// STACKIT project ID to which the network is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (Boolean) The Network Interface Security. If set to false, then no security groups will apply to this network interface.
	// The Network Interface Security. If set to false, then no security groups will apply to this network interface.
	// +kubebuilder:validation:Optional
	Security *bool `json:"security,omitempty" tf:"security,omitempty"`

	// (List of String) The list of security group UUIDs. If security is set to false, setting this field will lead to an error.
	// The list of security group UUIDs. If security is set to false, setting this field will lead to an error.
	// +kubebuilder:validation:Optional
	SecurityGroupIds []*string `json:"securityGroupIds,omitempty" tf:"security_group_ids,omitempty"`
}

// NetworkInterfaceSpec defines the desired state of NetworkInterface
type NetworkInterfaceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NetworkInterfaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NetworkInterfaceInitParameters `json:"initProvider,omitempty"`
}

// NetworkInterfaceStatus defines the observed state of NetworkInterface.
type NetworkInterfaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NetworkInterfaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NetworkInterface is the Schema for the NetworkInterfaces API. Network interface resource schema. Must have a region specified in the provider configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type NetworkInterface struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   NetworkInterfaceSpec   `json:"spec"`
	Status NetworkInterfaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NetworkInterfaceList contains a list of NetworkInterfaces
type NetworkInterfaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NetworkInterface `json:"items"`
}

// Repository type metadata.
var (
	NetworkInterface_Kind             = "NetworkInterface"
	NetworkInterface_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NetworkInterface_Kind}.String()
	NetworkInterface_KindAPIVersion   = NetworkInterface_Kind + "." + CRDGroupVersion.String()
	NetworkInterface_GroupVersionKind = CRDGroupVersion.WithKind(NetworkInterface_Kind)
)

func init() {
	SchemeBuilder.Register(&NetworkInterface{}, &NetworkInterfaceList{})
}
