// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ProjectInitParameters struct {

	// value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// To create a project within a STACKIT Network Area, setting the label networkArea=<networkAreaID> is required. This can not be changed after project creation.
	// Labels are key-value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// To create a project within a STACKIT Network Area, setting the label `networkArea=<networkAreaID>` is required. This can not be changed after project creation.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Project name.
	// Project name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Email address of the owner of the project. This value is only considered during creation. Changing it afterwards will have no effect.
	// Email address of the owner of the project. This value is only considered during creation. Changing it afterwards will have no effect.
	OwnerEmail *string `json:"ownerEmail,omitempty" tf:"owner_email,omitempty"`

	// friendly) and UUID are supported
	// Parent resource identifier. Both container ID (user-friendly) and UUID are supported
	ParentContainerID *string `json:"parentContainerId,omitempty" tf:"parent_container_id,omitempty"`
}

type ProjectObservation struct {

	// friendly identifier.
	// Project container ID. Globally unique, user-friendly identifier.
	ContainerID *string `json:"containerId,omitempty" tf:"container_id,omitempty"`

	// time at which the project was created.
	// Date-time at which the project was created.
	CreationTime *string `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// It is structured as "container_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// To create a project within a STACKIT Network Area, setting the label networkArea=<networkAreaID> is required. This can not be changed after project creation.
	// Labels are key-value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// To create a project within a STACKIT Network Area, setting the label `networkArea=<networkAreaID>` is required. This can not be changed after project creation.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Project name.
	// Project name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Email address of the owner of the project. This value is only considered during creation. Changing it afterwards will have no effect.
	// Email address of the owner of the project. This value is only considered during creation. Changing it afterwards will have no effect.
	OwnerEmail *string `json:"ownerEmail,omitempty" tf:"owner_email,omitempty"`

	// friendly) and UUID are supported
	// Parent resource identifier. Both container ID (user-friendly) and UUID are supported
	ParentContainerID *string `json:"parentContainerId,omitempty" tf:"parent_container_id,omitempty"`

	// (String) Project UUID identifier. This is the ID that can be used in most of the other resources to identify the project.
	// Project UUID identifier. This is the ID that can be used in most of the other resources to identify the project.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// time at which the project was last modified.
	// Date-time at which the project was last modified.
	UpdateTime *string `json:"updateTime,omitempty" tf:"update_time,omitempty"`
}

type ProjectParameters struct {

	// value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// To create a project within a STACKIT Network Area, setting the label networkArea=<networkAreaID> is required. This can not be changed after project creation.
	// Labels are key-value string pairs which can be attached to a resource container. A label key must match the regex [A-ZÄÜÖa-zäüöß0-9_-]{1,64}. A label value must match the regex ^$|[A-ZÄÜÖa-zäüöß0-9_-]{1,64}.
	// To create a project within a STACKIT Network Area, setting the label `networkArea=<networkAreaID>` is required. This can not be changed after project creation.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) Project name.
	// Project name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Email address of the owner of the project. This value is only considered during creation. Changing it afterwards will have no effect.
	// Email address of the owner of the project. This value is only considered during creation. Changing it afterwards will have no effect.
	// +kubebuilder:validation:Optional
	OwnerEmail *string `json:"ownerEmail,omitempty" tf:"owner_email,omitempty"`

	// friendly) and UUID are supported
	// Parent resource identifier. Both container ID (user-friendly) and UUID are supported
	// +kubebuilder:validation:Optional
	ParentContainerID *string `json:"parentContainerId,omitempty" tf:"parent_container_id,omitempty"`
}

// ProjectSpec defines the desired state of Project
type ProjectSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ProjectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProjectInitParameters `json:"initProvider,omitempty"`
}

// ProjectStatus defines the observed state of Project.
type ProjectStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProjectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Project is the Schema for the Projects API. Resource Manager project resource schema. -> In case you're getting started with an empty STACKIT organization and want to use this resource to create projects in it, check out this guide https://registry.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,stackit}
type Project struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ownerEmail) || (has(self.initProvider) && has(self.initProvider.ownerEmail))",message="spec.forProvider.ownerEmail is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.parentContainerId) || (has(self.initProvider) && has(self.initProvider.parentContainerId))",message="spec.forProvider.parentContainerId is a required parameter"
	Spec   ProjectSpec   `json:"spec"`
	Status ProjectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProjectList contains a list of Projects
type ProjectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Project `json:"items"`
}

// Repository type metadata.
var (
	Project_Kind             = "Project"
	Project_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Project_Kind}.String()
	Project_KindAPIVersion   = Project_Kind + "." + CRDGroupVersion.String()
	Project_GroupVersionKind = CRDGroupVersion.WithKind(Project_Kind)
)

func init() {
	SchemeBuilder.Register(&Project{}, &ProjectList{})
}
