apiVersion: resourcemanager.stackit.crossplane.io/v1alpha1
kind: Folder
metadata:
  annotations:
    meta.upbound.io/example-id: resourcemanager/v1alpha1/folder
  labels:
    testing.upbound.io/example-name: example-folder
  name: example-folder
spec:
  forProvider:
    name: example-folder
    parentContainerId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    ownerEmail: admin@example.com
