apiVersion: resourcemanager.stackit.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: resourcemanager/v1alpha1/project
  labels:
    testing.upbound.io/example-name: example-project
  name: example-project
spec:
  forProvider:
    name: example-project
    parentContainerId: fed80047-d03a-4fe8-9c67-94d68abaa648
    ownerEmail: uptest-dpildner-n8ejt1i8@sa.stackit.cloud
