apiVersion: resourcemanager.stackit.crossplane.io/v1alpha1
kind: Project
metadata:
  annotations:
    meta.upbound.io/example-id: resourcemanager/v1alpha1/project
  labels:
    testing.upbound.io/example-name: example-project
  name: example-project
spec:
  forProvider:
    name: example-project
    parentContainerId: <ORGANIZATION-ID>
    ownerEmail: <SA-EMAIL>
