apiVersion: compute.stackit.m.crossplane.io/v1alpha1
kind: Image
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1alpha1/image
  labels:
    testing.upbound.io/example-name: example_image
  name: example-image
  namespace: crossplane-system
spec:
  forProvider:
    diskFormat: qcow2
    localFilePath: ./path/to/image.qcow2
    minDiskSize: 10
    minRam: 5
    name: example-image
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
