apiVersion: git.stackit.crossplane.io/v1alpha1
kind: Git
metadata:
  annotations:
    meta.upbound.io/example-id: git/v1alpha1/git
  labels:
    testing.upbound.io/example-name: example-git
  name: example-git
spec:
  forProvider:
    name: example-git
    projectId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
