// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccessTokenInitParameters struct {

	// (String) The description of the access token
	// The description of the access token
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The displayed name of the access token
	// The displayed name of the access token
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) The Logs instance ID associated with the access token
	// The Logs instance ID associated with the access token
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/logs/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("instance_id",true)
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in logs to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in logs to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (Number) A lifetime period for an access token in days. If unset the token will not expire.
	// A lifetime period for an access token in days. If unset the token will not expire.
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`

	// (List of String) The access permissions granted to the access token. Possible values: read, write.
	// The access permissions granted to the access token. Possible values: `read`, `write`.
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) STACKIT project ID associated with the Logs access token
	// STACKIT project ID associated with the Logs access token
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) STACKIT region name the resource is located in. If not defined, the provider region is used.
	// STACKIT region name the resource is located in. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type AccessTokenObservation struct {

	// (String) The access token ID
	// The access token ID
	AccessTokenID *string `json:"accessTokenId,omitempty" tf:"access_token_id,omitempty"`

	// (String) The user who created the access token
	// The user who created the access token
	Creator *string `json:"creator,omitempty" tf:"creator,omitempty"`

	// (String) The description of the access token
	// The description of the access token
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The displayed name of the access token
	// The displayed name of the access token
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) Indicates if the access token can expire
	// Indicates if the access token can expire
	Expires *bool `json:"expires,omitempty" tf:"expires,omitempty"`

	// It is structured as "project_id,region,instance_id,access_token_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The Logs instance ID associated with the access token
	// The Logs instance ID associated with the access token
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// (Number) A lifetime period for an access token in days. If unset the token will not expire.
	// A lifetime period for an access token in days. If unset the token will not expire.
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`

	// (List of String) The access permissions granted to the access token. Possible values: read, write.
	// The access permissions granted to the access token. Possible values: `read`, `write`.
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) STACKIT project ID associated with the Logs access token
	// STACKIT project ID associated with the Logs access token
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) STACKIT region name the resource is located in. If not defined, the provider region is used.
	// STACKIT region name the resource is located in. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The status of the access token. Possible values are: active, expired.
	// The status of the access token. Possible values are: `active`, `expired`.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// (String) The date and time until an access token is valid to (inclusively)
	// The date and time until an access token is valid to (inclusively)
	ValidUntil *string `json:"validUntil,omitempty" tf:"valid_until,omitempty"`
}

type AccessTokenParameters struct {

	// (String) The description of the access token
	// The description of the access token
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The displayed name of the access token
	// The displayed name of the access token
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (String) The Logs instance ID associated with the access token
	// The Logs instance ID associated with the access token
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/logs/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("instance_id",true)
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in logs to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in logs to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (Number) A lifetime period for an access token in days. If unset the token will not expire.
	// A lifetime period for an access token in days. If unset the token will not expire.
	// +kubebuilder:validation:Optional
	Lifetime *float64 `json:"lifetime,omitempty" tf:"lifetime,omitempty"`

	// (List of String) The access permissions granted to the access token. Possible values: read, write.
	// The access permissions granted to the access token. Possible values: `read`, `write`.
	// +kubebuilder:validation:Optional
	Permissions []*string `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// (String) STACKIT project ID associated with the Logs access token
	// STACKIT project ID associated with the Logs access token
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) STACKIT region name the resource is located in. If not defined, the provider region is used.
	// STACKIT region name the resource is located in. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// AccessTokenSpec defines the desired state of AccessToken
type AccessTokenSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccessTokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessTokenInitParameters `json:"initProvider,omitempty"`
}

// AccessTokenStatus defines the observed state of AccessToken.
type AccessTokenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccessTokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessToken is the Schema for the AccessTokens API. Logs access token resource schema. Uses the default_region specified in the provider configuration as a fallback in case no region is defined on resource level.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type AccessToken struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   AccessTokenSpec   `json:"spec"`
	Status AccessTokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessTokenList contains a list of AccessTokens
type AccessTokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessToken `json:"items"`
}

// Repository type metadata.
var (
	AccessToken_Kind             = "AccessToken"
	AccessToken_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessToken_Kind}.String()
	AccessToken_KindAPIVersion   = AccessToken_Kind + "." + CRDGroupVersion.String()
	AccessToken_GroupVersionKind = CRDGroupVersion.WithKind(AccessToken_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessToken{}, &AccessTokenList{})
}
