apiVersion: rabbitmq.stackit.crossplane.io/v1alpha1
kind: Credential
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/credential
  labels:
    testing.upbound.io/example-name: example-rabbitmq-credential
  name: example-rabbitmq-credential
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-rabbitmq
    projectId: <PROJECT-ID>
  writeConnectionSecretToRef:
    name: rabbitmq-credentials
    namespace: default
