// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BasicAuthInitParameters struct {

	// (String, Sensitive) Specifies basic auth password.
	// Specifies basic auth password.
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (String) Specifies basic auth username.
	// Specifies basic auth username.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type BasicAuthObservation struct {

	// (String) Specifies basic auth username.
	// Specifies basic auth username.
	Username *string `json:"username,omitempty" tf:"username,omitempty"`
}

type BasicAuthParameters struct {

	// (String, Sensitive) Specifies basic auth password.
	// Specifies basic auth password.
	// +kubebuilder:validation:Optional
	PasswordSecretRef v1.LocalSecretKeySelector `json:"passwordSecretRef" tf:"-"`

	// (String) Specifies basic auth username.
	// Specifies basic auth username.
	// +kubebuilder:validation:Optional
	Username *string `json:"username" tf:"username,omitempty"`
}

type Saml2InitParameters struct {

	// (Boolean) Specifies if URL parameters are enabled. Defaults to true
	// Specifies if URL parameters are enabled. Defaults to `true`
	EnableURLParameters *bool `json:"enableUrlParameters,omitempty" tf:"enable_url_parameters,omitempty"`
}

type Saml2Observation struct {

	// (Boolean) Specifies if URL parameters are enabled. Defaults to true
	// Specifies if URL parameters are enabled. Defaults to `true`
	EnableURLParameters *bool `json:"enableUrlParameters,omitempty" tf:"enable_url_parameters,omitempty"`
}

type Saml2Parameters struct {

	// (Boolean) Specifies if URL parameters are enabled. Defaults to true
	// Specifies if URL parameters are enabled. Defaults to `true`
	// +kubebuilder:validation:Optional
	EnableURLParameters *bool `json:"enableUrlParameters,omitempty" tf:"enable_url_parameters,omitempty"`
}

type ScrapeconfigInitParameters struct {

	// (Attributes) A basic authentication block. (see below for nested schema)
	BasicAuth *BasicAuthInitParameters `json:"basicAuth,omitempty" tf:"basic_auth,omitempty"`

	// (String) Observability instance ID to which the scraping job is associated.
	// Observability instance ID to which the scraping job is associated.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/namespaced/observability/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("instance_id",true)
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in observability to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in observability to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (String) Specifies the job scraping url path. E.g. /metrics.
	// Specifies the job scraping url path. E.g. `/metrics`.
	MetricsPath *string `json:"metricsPath,omitempty" tf:"metrics_path,omitempty"`

	// (String) Specifies the name of the scraping job.
	// Specifies the name of the scraping job.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the scraping job is associated.
	// STACKIT project ID to which the scraping job is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) A SAML2 configuration block. (see below for nested schema)
	Saml2 *Saml2InitParameters `json:"saml2,omitempty" tf:"saml2,omitempty"`

	// (Number) Specifies the scrape sample limit. Upper limit depends on the service plan. Defaults to 5000.
	// Specifies the scrape sample limit. Upper limit depends on the service plan. Defaults to `5000`.
	SampleLimit *float64 `json:"sampleLimit,omitempty" tf:"sample_limit,omitempty"`

	// (String) Specifies the http scheme. Defaults to https.
	// Specifies the http scheme. Defaults to `https`.
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`

	// (String) Specifies the scrape interval as duration string. Defaults to 5m.
	// Specifies the scrape interval as duration string. Defaults to `5m`.
	ScrapeInterval *string `json:"scrapeInterval,omitempty" tf:"scrape_interval,omitempty"`

	// (String) Specifies the scrape timeout as duration string. Defaults to 2m.
	// Specifies the scrape timeout as duration string. Defaults to `2m`.
	ScrapeTimeout *string `json:"scrapeTimeout,omitempty" tf:"scrape_timeout,omitempty"`

	// (Attributes List) The targets list (specified by the static config). (see below for nested schema)
	Targets []TargetsInitParameters `json:"targets,omitempty" tf:"targets,omitempty"`
}

type ScrapeconfigObservation struct {

	// (Attributes) A basic authentication block. (see below for nested schema)
	BasicAuth *BasicAuthObservation `json:"basicAuth,omitempty" tf:"basic_auth,omitempty"`

	// It is structured as "project_id,instance_id,name".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Observability instance ID to which the scraping job is associated.
	// Observability instance ID to which the scraping job is associated.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// (String) Specifies the job scraping url path. E.g. /metrics.
	// Specifies the job scraping url path. E.g. `/metrics`.
	MetricsPath *string `json:"metricsPath,omitempty" tf:"metrics_path,omitempty"`

	// (String) Specifies the name of the scraping job.
	// Specifies the name of the scraping job.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the scraping job is associated.
	// STACKIT project ID to which the scraping job is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) A SAML2 configuration block. (see below for nested schema)
	Saml2 *Saml2Observation `json:"saml2,omitempty" tf:"saml2,omitempty"`

	// (Number) Specifies the scrape sample limit. Upper limit depends on the service plan. Defaults to 5000.
	// Specifies the scrape sample limit. Upper limit depends on the service plan. Defaults to `5000`.
	SampleLimit *float64 `json:"sampleLimit,omitempty" tf:"sample_limit,omitempty"`

	// (String) Specifies the http scheme. Defaults to https.
	// Specifies the http scheme. Defaults to `https`.
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`

	// (String) Specifies the scrape interval as duration string. Defaults to 5m.
	// Specifies the scrape interval as duration string. Defaults to `5m`.
	ScrapeInterval *string `json:"scrapeInterval,omitempty" tf:"scrape_interval,omitempty"`

	// (String) Specifies the scrape timeout as duration string. Defaults to 2m.
	// Specifies the scrape timeout as duration string. Defaults to `2m`.
	ScrapeTimeout *string `json:"scrapeTimeout,omitempty" tf:"scrape_timeout,omitempty"`

	// (Attributes List) The targets list (specified by the static config). (see below for nested schema)
	Targets []TargetsObservation `json:"targets,omitempty" tf:"targets,omitempty"`
}

type ScrapeconfigParameters struct {

	// (Attributes) A basic authentication block. (see below for nested schema)
	// +kubebuilder:validation:Optional
	BasicAuth *BasicAuthParameters `json:"basicAuth,omitempty" tf:"basic_auth,omitempty"`

	// (String) Observability instance ID to which the scraping job is associated.
	// Observability instance ID to which the scraping job is associated.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/namespaced/observability/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("instance_id",true)
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in observability to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in observability to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (String) Specifies the job scraping url path. E.g. /metrics.
	// Specifies the job scraping url path. E.g. `/metrics`.
	// +kubebuilder:validation:Optional
	MetricsPath *string `json:"metricsPath,omitempty" tf:"metrics_path,omitempty"`

	// (String) Specifies the name of the scraping job.
	// Specifies the name of the scraping job.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the scraping job is associated.
	// STACKIT project ID to which the scraping job is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Attributes) A SAML2 configuration block. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Saml2 *Saml2Parameters `json:"saml2,omitempty" tf:"saml2,omitempty"`

	// (Number) Specifies the scrape sample limit. Upper limit depends on the service plan. Defaults to 5000.
	// Specifies the scrape sample limit. Upper limit depends on the service plan. Defaults to `5000`.
	// +kubebuilder:validation:Optional
	SampleLimit *float64 `json:"sampleLimit,omitempty" tf:"sample_limit,omitempty"`

	// (String) Specifies the http scheme. Defaults to https.
	// Specifies the http scheme. Defaults to `https`.
	// +kubebuilder:validation:Optional
	Scheme *string `json:"scheme,omitempty" tf:"scheme,omitempty"`

	// (String) Specifies the scrape interval as duration string. Defaults to 5m.
	// Specifies the scrape interval as duration string. Defaults to `5m`.
	// +kubebuilder:validation:Optional
	ScrapeInterval *string `json:"scrapeInterval,omitempty" tf:"scrape_interval,omitempty"`

	// (String) Specifies the scrape timeout as duration string. Defaults to 2m.
	// Specifies the scrape timeout as duration string. Defaults to `2m`.
	// +kubebuilder:validation:Optional
	ScrapeTimeout *string `json:"scrapeTimeout,omitempty" tf:"scrape_timeout,omitempty"`

	// (Attributes List) The targets list (specified by the static config). (see below for nested schema)
	// +kubebuilder:validation:Optional
	Targets []TargetsParameters `json:"targets,omitempty" tf:"targets,omitempty"`
}

type TargetsInitParameters struct {

	// (Map of String) Specifies labels.
	// Specifies labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (List of String) Specifies target URLs.
	// Specifies target URLs.
	Urls []*string `json:"urls,omitempty" tf:"urls,omitempty"`
}

type TargetsObservation struct {

	// (Map of String) Specifies labels.
	// Specifies labels.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (List of String) Specifies target URLs.
	// Specifies target URLs.
	Urls []*string `json:"urls,omitempty" tf:"urls,omitempty"`
}

type TargetsParameters struct {

	// (Map of String) Specifies labels.
	// Specifies labels.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (List of String) Specifies target URLs.
	// Specifies target URLs.
	// +kubebuilder:validation:Optional
	Urls []*string `json:"urls" tf:"urls,omitempty"`
}

// ScrapeconfigSpec defines the desired state of Scrapeconfig
type ScrapeconfigSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ScrapeconfigParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ScrapeconfigInitParameters `json:"initProvider,omitempty"`
}

// ScrapeconfigStatus defines the observed state of Scrapeconfig.
type ScrapeconfigStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ScrapeconfigObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Scrapeconfig is the Schema for the Scrapeconfigs API. Observability scrape config resource schema. Must have a region specified in the provider configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,stackit}
type Scrapeconfig struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.metricsPath) || (has(self.initProvider) && has(self.initProvider.metricsPath))",message="spec.forProvider.metricsPath is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targets) || (has(self.initProvider) && has(self.initProvider.targets))",message="spec.forProvider.targets is a required parameter"
	Spec   ScrapeconfigSpec   `json:"spec"`
	Status ScrapeconfigStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ScrapeconfigList contains a list of Scrapeconfigs
type ScrapeconfigList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Scrapeconfig `json:"items"`
}

// Repository type metadata.
var (
	Scrapeconfig_Kind             = "Scrapeconfig"
	Scrapeconfig_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Scrapeconfig_Kind}.String()
	Scrapeconfig_KindAPIVersion   = Scrapeconfig_Kind + "." + CRDGroupVersion.String()
	Scrapeconfig_GroupVersionKind = CRDGroupVersion.WithKind(Scrapeconfig_Kind)
)

func init() {
	SchemeBuilder.Register(&Scrapeconfig{}, &ScrapeconfigList{})
}
