apiVersion: sfs.stackit.crossplane.io/v1alpha1
kind: Share
metadata:
  annotations:
    meta.upbound.io/example-id: sfs/v1alpha1/share
  labels:
    testing.upbound.io/example-name: example-sfs-share
  name: example-sfs-share
spec:
  forProvider:
    name: example-sfs-share
    projectId: 04ce9fde-6d4b-417d-8b31-f25850aefde6
    spaceHardLimitGigabytes: 100
    exportPolicy: read-write
    resourcePoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-sfs-pool
