apiVersion: sfs.stackit.crossplane.io/v1alpha1
kind: Share
metadata:
  labels:
    testing.upbound.io/example-name: example-sfs-share
  name: example-sfs-share
spec:
  forProvider:
    name: example-sfs-share
    projectId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    spaceHardLimitGigabytes: 100
    exportPolicy: read-write
    resourcePoolIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-sfs-pool
  providerConfigRef:
    name: default
