// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TokenInitParameters struct {

	// (Number) Expiration time of the token, in seconds. Minimum is 600, Maximum is 15552000. Defaults to 3600
	// Expiration time of the token, in seconds. Minimum is 600, Maximum is 15552000. Defaults to `3600`
	Expiration *float64 `json:"expiration,omitempty" tf:"expiration,omitempty"`

	// (String) ID of the Edge Cloud instance.
	// ID of the Edge Cloud instance.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/edgecloud/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("instance_id",true)
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in edgecloud to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in edgecloud to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (String) Name of the Edge Cloud instance.
	// Name of the Edge Cloud instance.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// (String) STACKIT project ID to which the Edge Cloud instance is associated.
	// STACKIT project ID to which the Edge Cloud instance is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Number of seconds before expiration to trigger recreation of the token at.
	// Number of seconds before expiration to trigger recreation of the token at.
	RecreateBefore *float64 `json:"recreateBefore,omitempty" tf:"recreate_before,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type TokenObservation struct {

	// time when the token was created
	// Date-time when the token was created
	CreationTime *string `json:"creationTime,omitempty" tf:"creation_time,omitempty"`

	// (Number) Expiration time of the token, in seconds. Minimum is 600, Maximum is 15552000. Defaults to 3600
	// Expiration time of the token, in seconds. Minimum is 600, Maximum is 15552000. Defaults to `3600`
	Expiration *float64 `json:"expiration,omitempty" tf:"expiration,omitempty"`

	// (String) Timestamp when the token expires
	// Timestamp when the token expires
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// It is structured as "project_id,region,instance_name or instance_id,token_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) ID of the Edge Cloud instance.
	// ID of the Edge Cloud instance.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// (String) Name of the Edge Cloud instance.
	// Name of the Edge Cloud instance.
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// (String) STACKIT project ID to which the Edge Cloud instance is associated.
	// STACKIT project ID to which the Edge Cloud instance is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Number of seconds before expiration to trigger recreation of the token at.
	// Number of seconds before expiration to trigger recreation of the token at.
	RecreateBefore *float64 `json:"recreateBefore,omitempty" tf:"recreate_before,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (string) internally generated uuid to identify a token resource in provider, since the edge cloud api doesnt return a token identifier
	// internally generated uuid to identify a token resource in provider, since the edge cloud api doesnt return a token identifier
	TokenID *string `json:"tokenId,omitempty" tf:"token_id,omitempty"`
}

type TokenParameters struct {

	// (Number) Expiration time of the token, in seconds. Minimum is 600, Maximum is 15552000. Defaults to 3600
	// Expiration time of the token, in seconds. Minimum is 600, Maximum is 15552000. Defaults to `3600`
	// +kubebuilder:validation:Optional
	Expiration *float64 `json:"expiration,omitempty" tf:"expiration,omitempty"`

	// (String) ID of the Edge Cloud instance.
	// ID of the Edge Cloud instance.
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/edgecloud/v1alpha1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("instance_id",true)
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in edgecloud to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v1.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in edgecloud to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v1.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// (String) Name of the Edge Cloud instance.
	// Name of the Edge Cloud instance.
	// +kubebuilder:validation:Optional
	InstanceName *string `json:"instanceName,omitempty" tf:"instance_name,omitempty"`

	// (String) STACKIT project ID to which the Edge Cloud instance is associated.
	// STACKIT project ID to which the Edge Cloud instance is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Number) Number of seconds before expiration to trigger recreation of the token at.
	// Number of seconds before expiration to trigger recreation of the token at.
	// +kubebuilder:validation:Optional
	RecreateBefore *float64 `json:"recreateBefore,omitempty" tf:"recreate_before,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// TokenSpec defines the desired state of Token
type TokenSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TokenParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TokenInitParameters `json:"initProvider,omitempty"`
}

// TokenStatus defines the observed state of Token.
type TokenStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TokenObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Token is the Schema for the Tokens API. Edge Cloud is in private Beta and not generally available. You can contact support if you are interested in trying it out. ~> This resource is in beta and may be subject to breaking changes in the future. Use with caution. See our guide https://registry.io/providers/stackitcloud/stackit/latest/docs/guides/opting_into_beta_resources for how to opt-in to use beta resources.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type Token struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   TokenSpec   `json:"spec"`
	Status TokenStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TokenList contains a list of Tokens
type TokenList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Token `json:"items"`
}

// Repository type metadata.
var (
	Token_Kind             = "Token"
	Token_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Token_Kind}.String()
	Token_KindAPIVersion   = Token_Kind + "." + CRDGroupVersion.String()
	Token_GroupVersionKind = CRDGroupVersion.WithKind(Token_Kind)
)

func init() {
	SchemeBuilder.Register(&Token{}, &TokenList{})
}
