// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ChecksumInitParameters struct {
}

type ChecksumObservation struct {

	// (String) Algorithm for the checksum of the image data.
	// Algorithm for the checksum of the image data.
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// (String) Hexdigest of the checksum of the image data.
	// Hexdigest of the checksum of the image data.
	Digest *string `json:"digest,omitempty" tf:"digest,omitempty"`
}

type ChecksumParameters struct {
}

type ConfigInitParameters struct {

	// (Boolean) Enables the BIOS bootmenu.
	// Enables the BIOS bootmenu.
	BootMenu *bool `json:"bootMenu,omitempty" tf:"boot_menu,omitempty"`

	// (String) Sets CDROM bus controller type.
	// Sets CDROM bus controller type.
	CdromBus *string `json:"cdromBus,omitempty" tf:"cdrom_bus,omitempty"`

	// (String) Sets Disk bus controller type.
	// Sets Disk bus controller type.
	DiskBus *string `json:"diskBus,omitempty" tf:"disk_bus,omitempty"`

	// (String) Sets virtual network interface model.
	// Sets virtual network interface model.
	NicModel *string `json:"nicModel,omitempty" tf:"nic_model,omitempty"`

	// (String) Enables operating system specific optimizations.
	// Enables operating system specific optimizations.
	OperatingSystem *string `json:"operatingSystem,omitempty" tf:"operating_system,omitempty"`

	// (String) Operating system distribution.
	// Operating system distribution.
	OperatingSystemDistro *string `json:"operatingSystemDistro,omitempty" tf:"operating_system_distro,omitempty"`

	// (String) Version of the operating system.
	// Version of the operating system.
	OperatingSystemVersion *string `json:"operatingSystemVersion,omitempty" tf:"operating_system_version,omitempty"`

	// (String) Sets the device bus when the image is used as a rescue image.
	// Sets the device bus when the image is used as a rescue image.
	RescueBus *string `json:"rescueBus,omitempty" tf:"rescue_bus,omitempty"`

	// (String) Sets the device when the image is used as a rescue image.
	// Sets the device when the image is used as a rescue image.
	RescueDevice *string `json:"rescueDevice,omitempty" tf:"rescue_device,omitempty"`

	// (Boolean) Enables Secure Boot.
	// Enables Secure Boot.
	SecureBoot *bool `json:"secureBoot,omitempty" tf:"secure_boot,omitempty"`

	// (Boolean) Enables UEFI boot.
	// Enables UEFI boot.
	Uefi *bool `json:"uefi,omitempty" tf:"uefi,omitempty"`

	// (String) Sets Graphic device model.
	// Sets Graphic device model.
	VideoModel *string `json:"videoModel,omitempty" tf:"video_model,omitempty"`

	// (Boolean) Enables the use of VirtIO SCSI to provide block device access. By default instances use VirtIO Block.
	// Enables the use of VirtIO SCSI to provide block device access. By default instances use VirtIO Block.
	VirtioScsi *bool `json:"virtioScsi,omitempty" tf:"virtio_scsi,omitempty"`
}

type ConfigObservation struct {

	// (Boolean) Enables the BIOS bootmenu.
	// Enables the BIOS bootmenu.
	BootMenu *bool `json:"bootMenu,omitempty" tf:"boot_menu,omitempty"`

	// (String) Sets CDROM bus controller type.
	// Sets CDROM bus controller type.
	CdromBus *string `json:"cdromBus,omitempty" tf:"cdrom_bus,omitempty"`

	// (String) Sets Disk bus controller type.
	// Sets Disk bus controller type.
	DiskBus *string `json:"diskBus,omitempty" tf:"disk_bus,omitempty"`

	// (String) Sets virtual network interface model.
	// Sets virtual network interface model.
	NicModel *string `json:"nicModel,omitempty" tf:"nic_model,omitempty"`

	// (String) Enables operating system specific optimizations.
	// Enables operating system specific optimizations.
	OperatingSystem *string `json:"operatingSystem,omitempty" tf:"operating_system,omitempty"`

	// (String) Operating system distribution.
	// Operating system distribution.
	OperatingSystemDistro *string `json:"operatingSystemDistro,omitempty" tf:"operating_system_distro,omitempty"`

	// (String) Version of the operating system.
	// Version of the operating system.
	OperatingSystemVersion *string `json:"operatingSystemVersion,omitempty" tf:"operating_system_version,omitempty"`

	// (String) Sets the device bus when the image is used as a rescue image.
	// Sets the device bus when the image is used as a rescue image.
	RescueBus *string `json:"rescueBus,omitempty" tf:"rescue_bus,omitempty"`

	// (String) Sets the device when the image is used as a rescue image.
	// Sets the device when the image is used as a rescue image.
	RescueDevice *string `json:"rescueDevice,omitempty" tf:"rescue_device,omitempty"`

	// (Boolean) Enables Secure Boot.
	// Enables Secure Boot.
	SecureBoot *bool `json:"secureBoot,omitempty" tf:"secure_boot,omitempty"`

	// (Boolean) Enables UEFI boot.
	// Enables UEFI boot.
	Uefi *bool `json:"uefi,omitempty" tf:"uefi,omitempty"`

	// (String) Sets Graphic device model.
	// Sets Graphic device model.
	VideoModel *string `json:"videoModel,omitempty" tf:"video_model,omitempty"`

	// (Boolean) Enables the use of VirtIO SCSI to provide block device access. By default instances use VirtIO Block.
	// Enables the use of VirtIO SCSI to provide block device access. By default instances use VirtIO Block.
	VirtioScsi *bool `json:"virtioScsi,omitempty" tf:"virtio_scsi,omitempty"`
}

type ConfigParameters struct {

	// (Boolean) Enables the BIOS bootmenu.
	// Enables the BIOS bootmenu.
	// +kubebuilder:validation:Optional
	BootMenu *bool `json:"bootMenu,omitempty" tf:"boot_menu,omitempty"`

	// (String) Sets CDROM bus controller type.
	// Sets CDROM bus controller type.
	// +kubebuilder:validation:Optional
	CdromBus *string `json:"cdromBus,omitempty" tf:"cdrom_bus,omitempty"`

	// (String) Sets Disk bus controller type.
	// Sets Disk bus controller type.
	// +kubebuilder:validation:Optional
	DiskBus *string `json:"diskBus,omitempty" tf:"disk_bus,omitempty"`

	// (String) Sets virtual network interface model.
	// Sets virtual network interface model.
	// +kubebuilder:validation:Optional
	NicModel *string `json:"nicModel,omitempty" tf:"nic_model,omitempty"`

	// (String) Enables operating system specific optimizations.
	// Enables operating system specific optimizations.
	// +kubebuilder:validation:Optional
	OperatingSystem *string `json:"operatingSystem,omitempty" tf:"operating_system,omitempty"`

	// (String) Operating system distribution.
	// Operating system distribution.
	// +kubebuilder:validation:Optional
	OperatingSystemDistro *string `json:"operatingSystemDistro,omitempty" tf:"operating_system_distro,omitempty"`

	// (String) Version of the operating system.
	// Version of the operating system.
	// +kubebuilder:validation:Optional
	OperatingSystemVersion *string `json:"operatingSystemVersion,omitempty" tf:"operating_system_version,omitempty"`

	// (String) Sets the device bus when the image is used as a rescue image.
	// Sets the device bus when the image is used as a rescue image.
	// +kubebuilder:validation:Optional
	RescueBus *string `json:"rescueBus,omitempty" tf:"rescue_bus,omitempty"`

	// (String) Sets the device when the image is used as a rescue image.
	// Sets the device when the image is used as a rescue image.
	// +kubebuilder:validation:Optional
	RescueDevice *string `json:"rescueDevice,omitempty" tf:"rescue_device,omitempty"`

	// (Boolean) Enables Secure Boot.
	// Enables Secure Boot.
	// +kubebuilder:validation:Optional
	SecureBoot *bool `json:"secureBoot,omitempty" tf:"secure_boot,omitempty"`

	// (Boolean) Enables UEFI boot.
	// Enables UEFI boot.
	// +kubebuilder:validation:Optional
	Uefi *bool `json:"uefi,omitempty" tf:"uefi,omitempty"`

	// (String) Sets Graphic device model.
	// Sets Graphic device model.
	// +kubebuilder:validation:Optional
	VideoModel *string `json:"videoModel,omitempty" tf:"video_model,omitempty"`

	// (Boolean) Enables the use of VirtIO SCSI to provide block device access. By default instances use VirtIO Block.
	// Enables the use of VirtIO SCSI to provide block device access. By default instances use VirtIO Block.
	// +kubebuilder:validation:Optional
	VirtioScsi *bool `json:"virtioScsi,omitempty" tf:"virtio_scsi,omitempty"`
}

type ImageInitParameters struct {

	// (Attributes) Properties to set hardware and scheduling settings for an image. (see below for nested schema)
	Config *ConfigInitParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (String) The disk format of the image.
	// The disk format of the image.
	DiskFormat *string `json:"diskFormat,omitempty" tf:"disk_format,omitempty"`

	// value string pairs which can be attached to a resource container
	// Labels are key-value string pairs which can be attached to a resource container
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The filepath of the raw image file to be uploaded.
	// The filepath of the raw image file to be uploaded.
	LocalFilePath *string `json:"localFilePath,omitempty" tf:"local_file_path,omitempty"`

	// (Number) The minimum disk size of the image in GB.
	// The minimum disk size of the image in GB.
	MinDiskSize *float64 `json:"minDiskSize,omitempty" tf:"min_disk_size,omitempty"`

	// (Number) The minimum RAM of the image in MB.
	// The minimum RAM of the image in MB.
	MinRAM *float64 `json:"minRam,omitempty" tf:"min_ram,omitempty"`

	// (String) The name of the image.
	// The name of the image.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the image is associated.
	// STACKIT project ID to which the image is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ImageObservation struct {

	// (Attributes) Representation of an image checksum. (see below for nested schema)
	Checksum *ChecksumObservation `json:"checksum,omitempty" tf:"checksum,omitempty"`

	// (Attributes) Properties to set hardware and scheduling settings for an image. (see below for nested schema)
	Config *ConfigObservation `json:"config,omitempty" tf:"config,omitempty"`

	// (String) The disk format of the image.
	// The disk format of the image.
	DiskFormat *string `json:"diskFormat,omitempty" tf:"disk_format,omitempty"`

	// It is structured as "project_id,region,image_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The image ID.
	// The image ID.
	ImageID *string `json:"imageId,omitempty" tf:"image_id,omitempty"`

	// value string pairs which can be attached to a resource container
	// Labels are key-value string pairs which can be attached to a resource container
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The filepath of the raw image file to be uploaded.
	// The filepath of the raw image file to be uploaded.
	LocalFilePath *string `json:"localFilePath,omitempty" tf:"local_file_path,omitempty"`

	// (Number) The minimum disk size of the image in GB.
	// The minimum disk size of the image in GB.
	MinDiskSize *float64 `json:"minDiskSize,omitempty" tf:"min_disk_size,omitempty"`

	// (Number) The minimum RAM of the image in MB.
	// The minimum RAM of the image in MB.
	MinRAM *float64 `json:"minRam,omitempty" tf:"min_ram,omitempty"`

	// (String) The name of the image.
	// The name of the image.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the image is associated.
	// STACKIT project ID to which the image is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (Boolean) Whether the image is protected.
	// Whether the image is protected.
	Protected *bool `json:"protected,omitempty" tf:"protected,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// (String) The scope of the image.
	// The scope of the image.
	Scope *string `json:"scope,omitempty" tf:"scope,omitempty"`
}

type ImageParameters struct {

	// (Attributes) Properties to set hardware and scheduling settings for an image. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Config *ConfigParameters `json:"config,omitempty" tf:"config,omitempty"`

	// (String) The disk format of the image.
	// The disk format of the image.
	// +kubebuilder:validation:Optional
	DiskFormat *string `json:"diskFormat,omitempty" tf:"disk_format,omitempty"`

	// value string pairs which can be attached to a resource container
	// Labels are key-value string pairs which can be attached to a resource container
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The filepath of the raw image file to be uploaded.
	// The filepath of the raw image file to be uploaded.
	// +kubebuilder:validation:Optional
	LocalFilePath *string `json:"localFilePath,omitempty" tf:"local_file_path,omitempty"`

	// (Number) The minimum disk size of the image in GB.
	// The minimum disk size of the image in GB.
	// +kubebuilder:validation:Optional
	MinDiskSize *float64 `json:"minDiskSize,omitempty" tf:"min_disk_size,omitempty"`

	// (Number) The minimum RAM of the image in MB.
	// The minimum RAM of the image in MB.
	// +kubebuilder:validation:Optional
	MinRAM *float64 `json:"minRam,omitempty" tf:"min_ram,omitempty"`

	// (String) The name of the image.
	// The name of the image.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) STACKIT project ID to which the image is associated.
	// STACKIT project ID to which the image is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// ImageSpec defines the desired state of Image
type ImageSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ImageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ImageInitParameters `json:"initProvider,omitempty"`
}

// ImageStatus defines the observed state of Image.
type ImageStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ImageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Image is the Schema for the Images API. Image resource schema. Must have a region specified in the provider configuration.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type Image struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.diskFormat) || (has(self.initProvider) && has(self.initProvider.diskFormat))",message="spec.forProvider.diskFormat is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.localFilePath) || (has(self.initProvider) && has(self.initProvider.localFilePath))",message="spec.forProvider.localFilePath is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	Spec   ImageSpec   `json:"spec"`
	Status ImageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ImageList contains a list of Images
type ImageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Image `json:"items"`
}

// Repository type metadata.
var (
	Image_Kind             = "Image"
	Image_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Image_Kind}.String()
	Image_KindAPIVersion   = Image_Kind + "." + CRDGroupVersion.String()
	Image_GroupVersionKind = CRDGroupVersion.WithKind(Image_Kind)
)

func init() {
	SchemeBuilder.Register(&Image{}, &ImageList{})
}
