// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PairInitParameters struct {

	// value string pairs which can be attached to a resource container.
	// Labels are key-value string pairs which can be attached to a resource container.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the SSH key pair.
	// The name of the SSH key pair.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// rsa <key_data> or ssh-ed25519 <key-data>.
	// A string representation of the public SSH key. E.g., `ssh-rsa <key_data>` or `ssh-ed25519 <key-data>`.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`
}

type PairObservation struct {

	// (String) The fingerprint of the public SSH key.
	// The fingerprint of the public SSH key.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// It takes the value of the key pair "name".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// value string pairs which can be attached to a resource container.
	// Labels are key-value string pairs which can be attached to a resource container.
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the SSH key pair.
	// The name of the SSH key pair.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// rsa <key_data> or ssh-ed25519 <key-data>.
	// A string representation of the public SSH key. E.g., `ssh-rsa <key_data>` or `ssh-ed25519 <key-data>`.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`
}

type PairParameters struct {

	// value string pairs which can be attached to a resource container.
	// Labels are key-value string pairs which can be attached to a resource container.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Labels map[string]*string `json:"labels,omitempty" tf:"labels,omitempty"`

	// (String) The name of the SSH key pair.
	// The name of the SSH key pair.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// rsa <key_data> or ssh-ed25519 <key-data>.
	// A string representation of the public SSH key. E.g., `ssh-rsa <key_data>` or `ssh-ed25519 <key-data>`.
	// +kubebuilder:validation:Optional
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`
}

// PairSpec defines the desired state of Pair
type PairSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PairParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PairInitParameters `json:"initProvider,omitempty"`
}

// PairStatus defines the observed state of Pair.
type PairStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PairObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Pair is the Schema for the Pairs API. Key pair resource schema. Must have a region specified in the provider configuration. Allows uploading an SSH public key to be used for server authentication. Usage with server
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type Pair struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.publicKey) || (has(self.initProvider) && has(self.initProvider.publicKey))",message="spec.forProvider.publicKey is a required parameter"
	Spec   PairSpec   `json:"spec"`
	Status PairStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PairList contains a list of Pairs
type PairList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Pair `json:"items"`
}

// Repository type metadata.
var (
	Pair_Kind             = "Pair"
	Pair_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Pair_Kind}.String()
	Pair_KindAPIVersion   = Pair_Kind + "." + CRDGroupVersion.String()
	Pair_GroupVersionKind = CRDGroupVersion.WithKind(Pair_Kind)
)

func init() {
	SchemeBuilder.Register(&Pair{}, &PairList{})
}
