// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Key.
func (mg *Key) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KeyringID),
		Extract:      resource.ExtractParamPath("keyring_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KeyringIDRef,
		Selector:     mg.Spec.ForProvider.KeyringIDSelector,
		To: reference.To{
			List:    &KeyringList{},
			Managed: &Keyring{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KeyringID")
	}
	mg.Spec.ForProvider.KeyringID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KeyringIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KeyringID),
		Extract:      resource.ExtractParamPath("keyring_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.KeyringIDRef,
		Selector:     mg.Spec.InitProvider.KeyringIDSelector,
		To: reference.To{
			List:    &KeyringList{},
			Managed: &Keyring{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KeyringID")
	}
	mg.Spec.InitProvider.KeyringID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KeyringIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this WrappingKey.
func (mg *WrappingKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KeyringID),
		Extract:      resource.ExtractParamPath("keyring_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KeyringIDRef,
		Selector:     mg.Spec.ForProvider.KeyringIDSelector,
		To: reference.To{
			List:    &KeyringList{},
			Managed: &Keyring{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KeyringID")
	}
	mg.Spec.ForProvider.KeyringID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KeyringIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KeyringID),
		Extract:      resource.ExtractParamPath("keyring_id", true),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.KeyringIDRef,
		Selector:     mg.Spec.InitProvider.KeyringIDSelector,
		To: reference.To{
			List:    &KeyringList{},
			Managed: &Keyring{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KeyringID")
	}
	mg.Spec.InitProvider.KeyringID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KeyringIDRef = rsp.ResolvedReference

	return nil
}
