// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type KeyInitParameters struct {

	// (String) The access scope of the key. Default is PUBLIC. Possible values are: PUBLIC, SNA.
	// The access scope of the key. Default is `PUBLIC`. Possible values are: `PUBLIC`, `SNA`.
	AccessScope *string `json:"accessScope,omitempty" tf:"access_scope,omitempty"`

	// (String) The encryption algorithm that the key will use to encrypt data. Possible values are: aes_256_gcm, rsa_2048_oaep_sha256, rsa_3072_oaep_sha256, rsa_4096_oaep_sha256, rsa_4096_oaep_sha512, hmac_sha256, hmac_sha384, hmac_sha512, ecdsa_p256_sha256, ecdsa_p384_sha384, ecdsa_p521_sha512.
	// The encryption algorithm that the key will use to encrypt data. Possible values are: `aes_256_gcm`, `rsa_2048_oaep_sha256`, `rsa_3072_oaep_sha256`, `rsa_4096_oaep_sha256`, `rsa_4096_oaep_sha512`, `hmac_sha256`, `hmac_sha384`, `hmac_sha512`, `ecdsa_p256_sha256`, `ecdsa_p384_sha384`, `ecdsa_p521_sha512`.
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// (String) A user chosen description to distinguish multiple keys
	// A user chosen description to distinguish multiple keys
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name to distinguish multiple keys
	// The display name to distinguish multiple keys
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) States whether versions can be created or only imported.
	// States whether versions can be created or only imported.
	ImportOnly *bool `json:"importOnly,omitempty" tf:"import_only,omitempty"`

	// (String) The ID of the associated keyring
	// The ID of the associated keyring
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/kms/v1alpha1.Keyring
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("keyring_id",true)
	KeyringID *string `json:"keyringId,omitempty" tf:"keyring_id,omitempty"`

	// Reference to a Keyring in kms to populate keyringId.
	// +kubebuilder:validation:Optional
	KeyringIDRef *v1.Reference `json:"keyringIdRef,omitempty" tf:"-"`

	// Selector for a Keyring in kms to populate keyringId.
	// +kubebuilder:validation:Optional
	KeyringIDSelector *v1.Selector `json:"keyringIdSelector,omitempty" tf:"-"`

	// (String) STACKIT project ID to which the key is associated.
	// STACKIT project ID to which the key is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The underlying system that is responsible for protecting the key material. Possible values are: software.
	// The underlying system that is responsible for protecting the key material. Possible values are: `software`.
	Protection *string `json:"protection,omitempty" tf:"protection,omitempty"`

	// (String) The purpose for which the key will be used. Possible values are: symmetric_encrypt_decrypt, asymmetric_encrypt_decrypt, message_authentication_code, asymmetric_sign_verify.
	// The purpose for which the key will be used. Possible values are: `symmetric_encrypt_decrypt`, `asymmetric_encrypt_decrypt`, `message_authentication_code`, `asymmetric_sign_verify`.
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type KeyObservation struct {

	// (String) The access scope of the key. Default is PUBLIC. Possible values are: PUBLIC, SNA.
	// The access scope of the key. Default is `PUBLIC`. Possible values are: `PUBLIC`, `SNA`.
	AccessScope *string `json:"accessScope,omitempty" tf:"access_scope,omitempty"`

	// (String) The encryption algorithm that the key will use to encrypt data. Possible values are: aes_256_gcm, rsa_2048_oaep_sha256, rsa_3072_oaep_sha256, rsa_4096_oaep_sha256, rsa_4096_oaep_sha512, hmac_sha256, hmac_sha384, hmac_sha512, ecdsa_p256_sha256, ecdsa_p384_sha384, ecdsa_p521_sha512.
	// The encryption algorithm that the key will use to encrypt data. Possible values are: `aes_256_gcm`, `rsa_2048_oaep_sha256`, `rsa_3072_oaep_sha256`, `rsa_4096_oaep_sha256`, `rsa_4096_oaep_sha512`, `hmac_sha256`, `hmac_sha384`, `hmac_sha512`, `ecdsa_p256_sha256`, `ecdsa_p384_sha384`, `ecdsa_p521_sha512`.
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// (String) A user chosen description to distinguish multiple keys
	// A user chosen description to distinguish multiple keys
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name to distinguish multiple keys
	// The display name to distinguish multiple keys
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// It is structured as "project_id,region,keyring_id,key_id".
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) States whether versions can be created or only imported.
	// States whether versions can be created or only imported.
	ImportOnly *bool `json:"importOnly,omitempty" tf:"import_only,omitempty"`

	// (String) The ID of the key
	// The ID of the key
	KeyID *string `json:"keyId,omitempty" tf:"key_id,omitempty"`

	// (String) The ID of the associated keyring
	// The ID of the associated keyring
	KeyringID *string `json:"keyringId,omitempty" tf:"keyring_id,omitempty"`

	// (String) STACKIT project ID to which the key is associated.
	// STACKIT project ID to which the key is associated.
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The underlying system that is responsible for protecting the key material. Possible values are: software.
	// The underlying system that is responsible for protecting the key material. Possible values are: `software`.
	Protection *string `json:"protection,omitempty" tf:"protection,omitempty"`

	// (String) The purpose for which the key will be used. Possible values are: symmetric_encrypt_decrypt, asymmetric_encrypt_decrypt, message_authentication_code, asymmetric_sign_verify.
	// The purpose for which the key will be used. Possible values are: `symmetric_encrypt_decrypt`, `asymmetric_encrypt_decrypt`, `message_authentication_code`, `asymmetric_sign_verify`.
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type KeyParameters struct {

	// (String) The access scope of the key. Default is PUBLIC. Possible values are: PUBLIC, SNA.
	// The access scope of the key. Default is `PUBLIC`. Possible values are: `PUBLIC`, `SNA`.
	// +kubebuilder:validation:Optional
	AccessScope *string `json:"accessScope,omitempty" tf:"access_scope,omitempty"`

	// (String) The encryption algorithm that the key will use to encrypt data. Possible values are: aes_256_gcm, rsa_2048_oaep_sha256, rsa_3072_oaep_sha256, rsa_4096_oaep_sha256, rsa_4096_oaep_sha512, hmac_sha256, hmac_sha384, hmac_sha512, ecdsa_p256_sha256, ecdsa_p384_sha384, ecdsa_p521_sha512.
	// The encryption algorithm that the key will use to encrypt data. Possible values are: `aes_256_gcm`, `rsa_2048_oaep_sha256`, `rsa_3072_oaep_sha256`, `rsa_4096_oaep_sha256`, `rsa_4096_oaep_sha512`, `hmac_sha256`, `hmac_sha384`, `hmac_sha512`, `ecdsa_p256_sha256`, `ecdsa_p384_sha384`, `ecdsa_p521_sha512`.
	// +kubebuilder:validation:Optional
	Algorithm *string `json:"algorithm,omitempty" tf:"algorithm,omitempty"`

	// (String) A user chosen description to distinguish multiple keys
	// A user chosen description to distinguish multiple keys
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) The display name to distinguish multiple keys
	// The display name to distinguish multiple keys
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Boolean) States whether versions can be created or only imported.
	// States whether versions can be created or only imported.
	// +kubebuilder:validation:Optional
	ImportOnly *bool `json:"importOnly,omitempty" tf:"import_only,omitempty"`

	// (String) The ID of the associated keyring
	// The ID of the associated keyring
	// +crossplane:generate:reference:type=github.com/intive/provider-stackit/apis/cluster/kms/v1alpha1.Keyring
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("keyring_id",true)
	// +kubebuilder:validation:Optional
	KeyringID *string `json:"keyringId,omitempty" tf:"keyring_id,omitempty"`

	// Reference to a Keyring in kms to populate keyringId.
	// +kubebuilder:validation:Optional
	KeyringIDRef *v1.Reference `json:"keyringIdRef,omitempty" tf:"-"`

	// Selector for a Keyring in kms to populate keyringId.
	// +kubebuilder:validation:Optional
	KeyringIDSelector *v1.Selector `json:"keyringIdSelector,omitempty" tf:"-"`

	// (String) STACKIT project ID to which the key is associated.
	// STACKIT project ID to which the key is associated.
	// +kubebuilder:validation:Optional
	ProjectID *string `json:"projectId,omitempty" tf:"project_id,omitempty"`

	// (String) The underlying system that is responsible for protecting the key material. Possible values are: software.
	// The underlying system that is responsible for protecting the key material. Possible values are: `software`.
	// +kubebuilder:validation:Optional
	Protection *string `json:"protection,omitempty" tf:"protection,omitempty"`

	// (String) The purpose for which the key will be used. Possible values are: symmetric_encrypt_decrypt, asymmetric_encrypt_decrypt, message_authentication_code, asymmetric_sign_verify.
	// The purpose for which the key will be used. Possible values are: `symmetric_encrypt_decrypt`, `asymmetric_encrypt_decrypt`, `message_authentication_code`, `asymmetric_sign_verify`.
	// +kubebuilder:validation:Optional
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// (String) The resource region. If not defined, the provider region is used.
	// The resource region. If not defined, the provider region is used.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// KeySpec defines the desired state of Key
type KeySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     KeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KeyInitParameters `json:"initProvider,omitempty"`
}

// KeyStatus defines the observed state of Key.
type KeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        KeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Key is the Schema for the Keys API. KMS Key resource schema. Uses the default_region specified in the provider configuration as a fallback in case no region is defined on resource level. This way we can ensure no key setups are deleted by accident and it gives you the option to recover your keys within the grace period.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stackit}
type Key struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.algorithm) || (has(self.initProvider) && has(self.initProvider.algorithm))",message="spec.forProvider.algorithm is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.projectId) || (has(self.initProvider) && has(self.initProvider.projectId))",message="spec.forProvider.projectId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protection) || (has(self.initProvider) && has(self.initProvider.protection))",message="spec.forProvider.protection is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.purpose) || (has(self.initProvider) && has(self.initProvider.purpose))",message="spec.forProvider.purpose is a required parameter"
	Spec   KeySpec   `json:"spec"`
	Status KeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KeyList contains a list of Keys
type KeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Key `json:"items"`
}

// Repository type metadata.
var (
	Key_Kind             = "Key"
	Key_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Key_Kind}.String()
	Key_KindAPIVersion   = Key_Kind + "." + CRDGroupVersion.String()
	Key_GroupVersionKind = CRDGroupVersion.WithKind(Key_Kind)
)

func init() {
	SchemeBuilder.Register(&Key{}, &KeyList{})
}
